/*********************************************************************
 * @fn      fx_devmon.c
 *
 * @brief   软元件/缓冲存储器批量监视模块实现
 *
 * @author  Generated by AI
 * @date    2026-03-16
 *********************************************************************/

#include "fx_devmon.h"
#include "html_components.h"
#include <string.h>
#include <stdio.h>
#include "index.h"
#include "ethernet_app.h"
#include "melsec_fx_tables.h"   /* FX_E0_E1_Tables：软元件编号范围(eStart/eEnd)校验 */
/*********************************************************************
 * 全局变量定义
 *********************************************************************/
static fx_devmon_config_t g_monitor_config;
static fx_devmon_row_t g_data_rows[FX_DEVMON_MAX_ROWS];
static uint8_t g_row_count = 0;

/* ── 监视数据的字节/字序约定（与 PLC 侧一致，改动前请先看第 4 条的实测方法）──
 * 1) UART 回帧的数据段是 ASCII 十六进制文本，由 HTTPS.c 的 Web_Usart_Handler
 *    先调 hex_str_to_intlend() 解码为二进制（ASCII "12AB" → 字节 0x12,0xAB，
 *    即 buf[0]=低字节、buf[1]=高字节）。
 * 2) 16 位字： word = buf[n] | (buf[n+1] << 8)           见 ..._16BIT_form
 * 3) 32 位整数/实数：低位字在前 —— word0 = buf[0..1]、word1 = buf[2..3]，
 *    value = (word1 << 16) | word0，即
 *    (buf[3]<<24)|(buf[2]<<16)|(buf[1]<<8)|buf[0]   见 ..._32BIT/REAL_form
 *    这与三菱 FX"32 位数据低位字在 D(n)"的约定一致。
 * 4) 实测确认：PLC 侧 D100=0x5678、D101=0x1234 → 页面应显示 305419896；
 *    实数：PLC 侧 D100=0xF5C3、D101=0x4048(即 3.14f) → 页面应显示 3.14。
 */
 


/*********************************************************************
 * 静态函数声明
 *********************************************************************/
static char* FX_DEVMON_GetDeviceTypeString(fx_devmon_device_type_t dev_type);
 
/*********************************************************************
 * @fn      FX_DEVMON_Init
 *
 * @brief   初始化监视模块
 *
 * @return  none
 */
void FX_DEVMON_Init(void)
{
    /* 初始化配置 */
    memset(&g_monitor_config, 0, sizeof(fx_devmon_config_t));
    
    /* 设置默认配置 */
    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_DEVICE;  /* 监视类型：软元件监视 */
    g_monitor_config.device_type = FX_DEVMON_DEV_D;            /* 软元件类型：数据寄存器D */
    g_monitor_config.device_number = 0;                        /* 软元件起始编号：0 */
    g_monitor_config.buffer_module = 0;                        /* 缓冲存储器模块号：0 */
    g_monitor_config.buffer_address = 0;                       /* 缓冲存储器起始地址：0 */
    g_monitor_config.buffer_hex = 0;                           /* 缓冲存储器地址格式：10进制 */
    g_monitor_config.form = FX_DEVMON_FORM_WORD;               /* 监视格式：位＆字 */
    g_monitor_config.display = FX_DEVMON_DISP_16BIT;           /* 显示格式：16位整数 */
    g_monitor_config.value_format = FX_DEVMON_VAL_DECIMAL;     /* 数值格式：10进制 */
    g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_F0;       /* 位顺序：F-0（高位在前） */
    g_monitor_config.update_interval = FX_DEVMON_DEFAULT_INTERVAL; /* 自动更新间隔：默认5秒 */
    
    /* 清空数据 */
    memset(g_data_rows, 0, sizeof(g_data_rows));
    g_row_count = 0;
 
}

// ==================== MC协议设备代码转换函数 ====================
 
/**
 * @brief 判断软元件类型是否为字软元件（支持单字写入）
 * @param device_type 软元件类型
 * @return 1-是字软元件(D,R,T,C)，0-是位软元件(X,Y,M,S等)
 */
uint8_t FX_DEVMON_IsWordDevice(uint8_t device_type)
{
    return (device_type == FX_DEVMON_DEV_D || device_type == FX_DEVMON_DEV_R ||
            device_type == FX_DEVMON_DEV_T || device_type == FX_DEVMON_DEV_C);
}

/**
 * @brief 调整C200～C234软元件点数（32位软元件）
 * @param device_type 软元件类型
 * @param start_device 起始软元件编号
 * @param device_count 原始点数
 * @return 调整后的点数
 */
uint16_t FX_DEVMON_Adjust32BitCounterCount(uint8_t device_type, uint16_t start_device, uint16_t device_count)
{
    if (device_type == FX_DEVMON_DEV_C && start_device >= 200) {
        DEVMON_DEBUG("C200～C234 32位 软元件 点数=%d\r\n", device_count);
        if (device_count % 2 == 1) {
            DEVMON_DEBUG(" 软元件点数是奇数, 错误代码57H\r\n");
        }
        return device_count * 2;
    }
    return device_count;
}

/*********************************************************************
 * @fn      FX_DEVMON_GetConfig
 *
 * @brief   获取监控配置
 *
 * @return  监控配置指针
 */
fx_devmon_config_t* FX_DEVMON_GetConfig(void)
{
    return &g_monitor_config;
}

/*********************************************************************
 * @fn      FX_DEVMON_SetConfig
 *
 * @brief   设置监控配置
 *
 * @param   config - 配置指针
 *
 * @return  none
 */
void FX_DEVMON_SetConfig(fx_devmon_config_t* config)
{
    if (config != NULL) {
        memcpy(&g_monitor_config, config, sizeof(fx_devmon_config_t));
    }
}
 
/*********************************************************************
 * @fn      FX_DEVMON_GetRow
 *
 * @brief   获取数据行
 *
 * @param   row_index - 行索引
 *
 * @return  数据行指针
 */
fx_devmon_row_t* FX_DEVMON_GetRow(uint8_t row_index)
{
    if (row_index < FX_DEVMON_MAX_ROWS) {
        return &g_data_rows[row_index];
    }
    return NULL;
}

/*********************************************************************
 * @fn      FX_DEVMON_SetRow
 *
 * @brief   设置数据行
 *
 * @param   row_index - 行索引
 * @param   row - 数据行指针
 *
 * @return  none
 */
void FX_DEVMON_SetRow(uint16_t row_index )
{   
    g_row_count = row_index;
    if ( g_row_count >= FX_DEVMON_MAX_ROWS  ) {
        g_row_count = FX_DEVMON_MAX_ROWS;
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_ClearData
 *
 * @brief   清除数据
 *
 * @return  none
 */
void FX_DEVMON_ClearData(void)
{
    memset(g_data_rows, 0, sizeof(g_data_rows));
    g_row_count = 0;
}

/*********************************************************************
 * @fn      FX_DEVMON_GetDeviceTypeString
 *
 * @brief   获取软元件类型字符串
 *
 * @param   dev_type - 软元件类型
 *
 * @return  类型字符串
 */
static char* FX_DEVMON_GetDeviceTypeString(fx_devmon_device_type_t dev_type)
{
    switch (dev_type) {
        case FX_DEVMON_DEV_D: return "D";
        case FX_DEVMON_DEV_R: return "R";
        case FX_DEVMON_DEV_X: return "X";
        case FX_DEVMON_DEV_Y: return "Y";
        case FX_DEVMON_DEV_M: return "M";
        case FX_DEVMON_DEV_S: return "S";
        case FX_DEVMON_DEV_T: return "T";
        case FX_DEVMON_DEV_C: return "C";
        default: return "D";
    }
}
 

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor
 *
 * @brief   更新监控数据
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_CMD(uint8_t Sour_Sock ,uint8_t  Dest_Sock )
{
 
    //发送数据指令到PLC 通过网页选择的软元件/缓冲存储器起始地址和结束地址发送数据
    if( g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER)  /* 监视类型 */
    {
        /* 缓冲存储器 */
        DEVMON_DEBUG("监听 缓冲存储器:模块号=%d ",g_monitor_config.buffer_module );
        if( g_monitor_config.buffer_hex ){
            DEVMON_DEBUG("起始地址= %d \r\n", g_monitor_config.buffer_address );
        }else{
            DEVMON_DEBUG("起始地址= 0x%04X \r\n", g_monitor_config.buffer_address );
        }
        // 设置 缓冲存储器 数据表格行数量
        if( g_monitor_config.buffer_address + FX_DEVMON_MAX_ROWS <= 32639 )
        {
            FX_DEVMON_SetRow( FX_DEVMON_MAX_ROWS );
        }else{
            FX_DEVMON_SetRow( 32639 - g_monitor_config.buffer_address );
        }
    }
    else  
    {
        uint8_t device_type = g_monitor_config.device_type;               //软元件类型

        uint16_t device_number = g_monitor_config.device_number;         //软元件编号

        uint16_t device_count = FX_DEVMON_MAX_ROWS;                       //软元件/缓冲存储器数量 

#ifdef _FX_DEVMON_DEBUG
        char *device_name = FX_DEVMON_GetDeviceTypeString(g_monitor_config.device_type);
#endif
        // 根据软元件名 解析软元件类型
       // uint8_t MC_device_type = FX_DEVMON_DeviceCodeToType(device_type);
        /* ★ 行数/请求点数按"软元件真实编号范围"裁剪。
         * 原实现 map_max_addr 恒为 0（死代码），判断永远走 else，靠 uint16 回绕 +
         * SetRow 内部钳位侥幸得到行数，"地址范围校验"实际从未生效。
         * 现从 E0/E1 映射表取该软元件类型的最大编号 eEnd(melsec_fx_tables.h)：
         *   表中无此类型 或 起始编号越界   → 不监视(0 行，页面不显示数据行)
         *   起始编号 + MAX_ROWS - 1 <= eEnd → 满行
         *   否则按剩余点数裁剪               → 同时缩短 MC 请求点数，
         *                                      避免读到 PLC 最大地址之外被回错误码
         */
        {
            uint16_t dev_end = 0;
            uint16_t rows;
            uint8_t  k;

            for (k = 0; k < TABLE_E0_E1_SIZE; k++) {
                if (FX_E0_E1_Tables[k].e_code == net_mc_meta.device_name) {
                    dev_end = FX_E0_E1_Tables[k].eEnd;
                    break;
                }
            }

            if (k >= TABLE_E0_E1_SIZE || device_number > dev_end) {
                DEVMON_DEBUG("软元件类型/起始编号非法: code=0x%04X num=%d\r\n",
                             net_mc_meta.device_name, device_number);
                rows = 0;
            } else if (((uint32_t)device_number + (uint32_t)FX_DEVMON_MAX_ROWS - 1u) <= (uint32_t)dev_end) {
                rows = FX_DEVMON_MAX_ROWS;
            } else {
                rows = (uint16_t)(dev_end - device_number + 1u);
            }

            FX_DEVMON_SetRow(rows);
            device_count = rows;      /* 请求点数与显示行数保持一致 */
        }
#ifdef _FX_DEVMON_DEBUG
        DEVMON_DEBUG("device_name:0x%04X\r\n", net_mc_meta.device_name);   /* 原引用已注释掉的 MC_device_type，会导致 -D_FX_DEVMON_DEBUG 编译失败 */

        DEVMON_DEBUG("监听 软元件 %s:%d \r\n",device_name,g_monitor_config.device_number );

        DEVMON_DEBUG("监视格式= %d 显示=%d 进制数=%d,位顺序=%d",
                                    g_monitor_config.form ,
                                    g_monitor_config.display ,
                                    g_monitor_config.value_format ,
                                    g_monitor_config.bit_order);
#endif
        //统一用 字单位的成批读出,只是在显示的时候不一样..
        if ( device_type == FX_DEVMON_DEV_C  ) 
        {
            if( device_number >= 200 ) 
            { 
                if( device_number + device_count > 234 )
                {
                    // 调整C200～C234 软元件点数 读取范围控制 200 -234 
                    device_count = 234 - device_number; // 起始地址 + 长度 <= 234
                } 
                // 调整C200～C234软元件点数（32位软元件）
                device_count *= 2;
            }
            else if( device_number + device_count > 200 )
            {
                // 调整C0～C199软元件点数（16位软元件）读取范围控制 0-199
                device_count = 200 - device_number; // 起始地址 + 长度 <= 199 
            }
        }

        if (device_type == FX_DEVMON_DEV_R) {
            MELSEC_FX_BuildE06ReadCmd( Sour_Sock,Dest_Sock,device_number, device_count);
        } else {
            MELSEC_FX_BuildE00ReadCmd( Sour_Sock,Dest_Sock,device_number, device_count);
        }
    }
} 

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_ASCII_form
 *
 * @brief   更新监控数据 - ASCII格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_ASCII_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows REALASCII_form \r\n" );
    /* 更新ASCII格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index < len; i++)
    {
        // 存储ASCII字符
        g_data_rows[i].word_value = 0;
        if (buff_index + 1 < len) {
            // 存储两个ASCII字符到一个16位值中
            g_data_rows[i].word_value = (buff[buff_index] << 8) | buff[buff_index + 1];
            buff_index += 2;
            DEVMON_DEBUG("%X\r\n",g_data_rows[i].word_value );
        }
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        
        // 计算位值
        DEVMON_DEBUG("bit_[%d]:",i  );
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_REAL_form
 *
 * @brief   更新监控数据 - 实数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_REAL_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows REAL_form \r\n" );
    /* 更新实数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 3 < len; i++)
    {
        // 存储32位实数
        union {
            float f;
            uint32_t u;
        } real_value;
        
        real_value.u = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                      (buff[buff_index+1] << 8) | buff[buff_index];
        DEVMON_DEBUG("%f\r\n",real_value.f );
        // 将实数转换为整数存储（实际应用中可能需要调整）
        /* 保存浮点的"原始位模式"而不是截断后的整数（原写法把 3.14 显示成 3）。
         * 页面按 float 解释该 32 位值；字序约定见文件开头说明。 */
        g_data_rows[i].word_value = real_value.u;
        buff_index += 4;
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_32BIT_form
 *
 * @brief   更新监控数据 - 32位整数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_32BIT_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    
    DEVMON_DEBUG("g_data_rows 32BIT_form \r\n" );
    /* 更新32位整数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 3 < len; i++)
    {
        // 存储32位整数
        g_data_rows[i].word_value = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                                   (buff[buff_index+1] << 8) | buff[buff_index];
        buff_index += 4;
        DEVMON_DEBUG("%X\r\n",g_data_rows[i].word_value );
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;

        DEVMON_DEBUG("bit_[%d]:",i  );
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_16BIT_form
 *
 * @brief   更新监控数据 - 16位整数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_16BIT_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows 16BIT_form \r\n" );
    /* 更新16位整数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 1 < len; i++)
    {
        // 字单位的成批读出
        if (device_type == FX_DEVMON_DEV_C && device_number >= 200)
        {
            // C200～C234 (32位软元件)
            if (buff_index + 3 < len) {
                g_data_rows[i].word_value = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                                           (buff[buff_index+1] << 8) | buff[buff_index];
                buff_index += 4;
                DEVMON_DEBUG(" %X ", g_data_rows[i].word_value );
            }
        }
        else
        {
            // 16位软元件
            g_data_rows[i].word_value = (buff[buff_index+1] << 8) | buff[buff_index];
            buff_index += 2;
            DEVMON_DEBUG(" %X ", g_data_rows[i].word_value );
        }
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        DEVMON_DEBUG("bit_[%d]:",i  );
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
        DEVMON_DEBUG("\r\n");
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data
 *
 * @brief   更新监控数据主函数
 *
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data(u8 *buff, u16 len)
{
    /* 检查缓冲区是否为空 */
    if (buff == NULL || len == 0) {
        DEVMON_DEBUG("数据缓冲区为空\r\n");
        return;
    }
    
    // 发送数据指令到PLC 通过网页选择的软元件/缓冲存储器起始地址和结束地址发送数据
    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER)  /* 监视类型 */
    {
        /* 缓冲存储器 */
        DEVMON_DEBUG("监听 缓冲存储器:模块号=%d ", g_monitor_config.buffer_module);
        if (g_monitor_config.buffer_hex) {
            DEVMON_DEBUG("起始地址= %d \r\n", g_monitor_config.buffer_address);
        } else {
            DEVMON_DEBUG("起始地址= 0x%04X \r\n", g_monitor_config.buffer_address);
        }
        
        // 缓冲存储器数据处理（这里可以根据实际需求实现）
        u16 buff_index = 0;
        for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 1 < len; i++) {
            g_data_rows[i].word_value = (buff[buff_index+1] << 8) | buff[buff_index];
            g_data_rows[i].device_number = g_monitor_config.buffer_address + i;
            buff_index += 2;
            
            // 计算位值
            for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
                g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            }
        }
    }
    else  
    {
        uint8_t device_type = g_monitor_config.device_type;               // 软元件类型

        DEVMON_DEBUG("监视格式= %d 显示=%d 进制数=%d,位顺序=%d \r\n",
                                    g_monitor_config.form,
                                    g_monitor_config.display,
                                    g_monitor_config.value_format,
                                    g_monitor_config.bit_order);

        // 根据显示格式调用相应的处理函数
        switch (g_monitor_config.display) {
            case FX_DEVMON_DISP_16BIT:  // 16位整数
                FX_DEVMON_UpdateMonitor_Data_16BIT_form(device_type, buff, len);
                break;
            case FX_DEVMON_DISP_32BIT:  // 32位整数
                FX_DEVMON_UpdateMonitor_Data_32BIT_form(device_type, buff, len);
                break;
            case FX_DEVMON_DISP_REAL:    // 实数(32位)
                FX_DEVMON_UpdateMonitor_Data_REAL_form(device_type, buff, len);
                break;
            case FX_DEVMON_DISP_ASCII:   // ASCII字符
                FX_DEVMON_UpdateMonitor_Data_ASCII_form(device_type, buff, len);
                break;
            default:
                DEVMON_DEBUG("未知的显示格式: %d\r\n", g_monitor_config.display);
                break;
        }
    }
}


/*********************************************************************
 * @fn      FX_DEVMON_SendData_Table_Name
 *
 * @brief   发送数据行 软件表头 名称 
 *
 * @param   dev_name - 名称
 *          index_row - 起始行索引
 *
 * @return  none
 */
static uint16_t FX_DEVMON_SendData_Table_Name(char * dev_name , uint16_t index)
{
    uint16_t offset = 0;
    if (dev_name == NULL ) return 0;
    /* 行头 名称 */
    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE) 
    {
        /* 软元件 名称 */
        /* 取类型前缀(D/R/X/Y/M/S/T/C)的长度作为偏移：下面用 dev_name + offset 追加编号。
         * 原实现丢弃了 sprintf 的返回值(offset 恒为 0)，编号从 dev_name[0] 开始写，
         * 把刚写好的类型前缀覆盖掉 -> 页面"软元件"列只剩编号(如 4/7)而没有 D4/D7。 */
        offset = (uint16_t)sprintf(dev_name, "%s", FX_DEVMON_GetDeviceTypeString(g_monitor_config.device_type));
        switch (g_monitor_config.form) 
        {
        case FX_DEVMON_FORM_BIT:
            if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type) )
            {
                //字软元件 D,R,T,C
                offset += sprintf(dev_name + offset, "%d.%02d",g_monitor_config.device_number + index/16, index%16);
            }else{
                //位软元件 X,Y,M,S等
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y)
                {
                    //XY 8进制 
                    offset += sprintf(dev_name + offset, "%d%d",g_monitor_config.device_number + index%8, index/8);
                }else{ //M,S,T,C 10进制
                    offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number );
                }
            }
            break;
        case FX_DEVMON_FORM_WORD:
            if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type) )
            {
                //字软元件 D,R,T,C
                offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index);  
            }else{
                //位软元件 X,Y,M,S等
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y)
                {
                    //XY 8进制 
                    offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index/8 );
                }else{ //M,S,T,C 10进制
                    offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index/10 );
                }
            }
            break;
        case FX_DEVMON_FORM_BIT_8_10:
            if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type) )
            {
                //字软元件 D,R,T,C
                offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index*8);
            }else{
                //位软元件 X,Y,M,S等
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y)
                {
                    //8进制XY 
                    offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index*200 );
                }else{ //M,S,T,C 10进制
                    offset += sprintf(dev_name + offset, "%d",g_monitor_config.device_number + index*8*10 );
                }
            }
        break;
        }
                
    } else {
        /* 缓冲存储器 名称*/
        sprintf(dev_name, "U%d\\G%d", g_monitor_config.buffer_module,g_monitor_config.buffer_address + index * 16);
    }

    return strlen( dev_name );
}

/*********************************************************************
 * @fn      FX_DEVMON_SendDataRows
 *
 * @brief   发送数据行到指定范围
 *
 * @param   Dest_Sock - Socket ID
 *          start_row - 起始行索引
 *          end_row - 结束行索引
 *
 * @return  none
 */
static void FX_DEVMON_SendDataRows(uint8_t Dest_Sock, int start_row, int end_row)
{
    char *temp_buffer = HtmlBuffer;
    char dev_name[32];
 
    uint32_t offset;
    int i, j;
    
    offset = 0;
    DEVMON_DEBUG(" SendDataRows START:%d-END:%d\n",start_row,end_row);
    for (i = start_row; i < end_row && i < g_row_count; i++) 
    {
        // 软元件名称.
        FX_DEVMON_SendData_Table_Name ( dev_name, i );
        DEVMON_DEBUG("name:%s\n",dev_name);
       // 开始拼接 HTML 代码
        offset = 0;
        offset += sprintf(temp_buffer + offset, "<tr>");
        /* 软元件名称 */    
        offset += sprintf(temp_buffer + offset, "<td>%s</td>", dev_name);

        /* 监视格式 */
        switch (g_monitor_config.form)
        {
        case FX_DEVMON_FORM_BIT:   /* 位 */
        
            // 只显示第0位
            offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[0]);
            // 数值
            if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
                offset += sprintf(temp_buffer + offset, "<td>%04X</td>\r\n", (uint16_t)(g_data_rows[i].word_value & 0xFFFF));
            } else {
                offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)g_data_rows[i].word_value);
            }
            break;
            
        case FX_DEVMON_FORM_WORD:        /* 位&字 */
            // 显示所有16位
            if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type) )
            {
                //字软元件 D,R,T,C
                if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                    for (j = 0; j < 16; j++) {
                        offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[15 - j]);
                    }
                } else {
                    /* 0-F 顺序 */
                    for (j = 0; j < 16; j++) {
                        offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[j]);
                    }
                }
                // 数值
                if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
                    offset += sprintf(temp_buffer + offset, "<td>%04X</td>\r\n", (uint16_t)(g_data_rows[i].word_value & 0xFFFF));
                } else {
                    offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)g_data_rows[i].word_value);
                }
                
            }else{
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y)
                {
                    //8进制XY 
                   if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                        for (j = 0; j < 8; j++) {
                            offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[8 - j]);
                        }
                    } else {
                        /* 0-F 顺序 */
                        for (j = 0; j < 8; j++) {
                            offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[j]);
                        }
                    }
                    // 数值 8位
                    if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
                        offset += sprintf(temp_buffer + offset, "<td>%04X</td>\r\n", (uint16_t)(g_data_rows[i].word_value & 0xFF));
                    } else {
                        offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)g_data_rows[i].word_value);
                    }
                }else{ 
                    //M,S,T,C 10进制
                     if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                        for (j = 0; j < 10; j++) {
                            offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[10 - j]);
                        }
                    } else {
                        /* 0-F 顺序 */
                        for (j = 0; j < 10; j++) {
                            offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[j]);
                        }
                    }
                    // 数值10位
                    if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
                        offset += sprintf(temp_buffer + offset, "<td>%04X</td>\r\n", (uint16_t)(g_data_rows[i].word_value & 0x3FF));
                    } else {
                        offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)(g_data_rows[i].word_value & 0x3FF));
                    }
                }
            }
            break;
        case FX_DEVMON_FORM_BIT_8_10:    /* 位(8/10点) */
            //字软元件 D,R,T,C 每一个位都显示16位数据
            if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                /* F-0 顺序 */
                for (j = 0; j < 8; j++) {
                    offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[8-i].word_value);
                }
            } else {
                /* 0-F 顺序 */
                for (j = 0; j < 16; j++) {
                    offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].word_value);
                }
            }
            // 数值
            if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
                offset += sprintf(temp_buffer + offset, "<td>%04X%04X%04X%04X%04X%04X%04X%04X</td>\r\n", 
                                                                g_data_rows[i].word_value ,
                                                                g_data_rows[i+1].word_value,
                                                                g_data_rows[i+2].word_value,
                                                                g_data_rows[i+3].word_value,
                                                                g_data_rows[i+4].word_value,
                                                                g_data_rows[i+5].word_value,
                                                                g_data_rows[i+6].word_value,
                                                                g_data_rows[i+7].word_value);
            } else {
                offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)g_data_rows[i].word_value);
            }
            i += 8;

            break;
            
        default:
            // 默认情况，显示所有16位和数值
            for (j = 0; j < 16; j++) {
                offset += sprintf(temp_buffer + offset, "<td class=\"c0\">%d</td>", g_data_rows[i].bit_values[j]);
            }
            offset += sprintf(temp_buffer + offset, "<td>%d</td>\r\n", (int)g_data_rows[i].word_value);
            break;
        }
        /* 注释 */
        offset += sprintf(temp_buffer + offset, "</tr>\r\n");

        /* 数据量达到阈值时发送 */
        if (offset > 900) {
            Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
            offset = 0;
        }
    }
    
    /* 空行处理 */
    for (i = (g_row_count > start_row ? g_row_count : start_row); i < end_row && i < FX_DEVMON_MAX_ROWS; i++)
    {
        offset += sprintf(temp_buffer + offset, "<tr>\r\n");
        offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
        
        // 根据监视格式显示正确数量的空位列
        switch (g_monitor_config.form)
        {
        case FX_DEVMON_FORM_BIT:   /* 位 */
            // 只显示1个空位列
            offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
            break;
            
        case FX_DEVMON_FORM_WORD:   /* 位&字 */
            // 显示8个空位列
            for (j = 0; j < 8; j++) {
                offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
            }
            break;
            
        case FX_DEVMON_FORM_BIT_8_10:   /* 位(8/10点) */
            // 显示16个空位列
            for (j = 0; j < 16; j++) {
                offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
            }
            break;
            
        default:
            // 默认显示16个空位列
            for (j = 0; j < 16; j++) {
                offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
            }
            break;
        }
        
        offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
        offset += sprintf(temp_buffer + offset, "<td>&nbsp;</td>\r\n");
        offset += sprintf(temp_buffer + offset, "</tr>\r\n");
        
        if (offset > 900) {
            Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
            offset = 0;
        }
    }
    
    /* 发送剩余数据 */
    if (offset > 0) {
        Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    }

}
/*********************************************************************
 * @fn      FX_DEVMON_SendData_Table
 *
 * @brief   发送数据表格表头
 *
 * @param   Dest_Sock - Socket ID
 *
 * @return  none
 */
static void FX_DEVMON_SendData_Table(uint8_t Dest_Sock)
{
    /* 发送数据表格表头 */
    char *buffer = HtmlBuffer;
    uint32_t offset = 0;
    uint8_t num = 0;
    // 表格容器
    offset += sprintf(buffer + offset, "<div style=\"overflow:auto; height:400px; width:840px; margin:0 auto\">\r\n");
    // 表格开始
    offset += sprintf(buffer + offset, "<table border=\"1\" rules=\"all\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed; font-size:12px\">\r\n");
    // 表头开始
    offset += sprintf(buffer + offset, "<thead>\r\n");
    
    // 第一列标题
    offset += sprintf(buffer + offset, "<tr>\r\n<td width=\"80\">%s</td>\r\n", 
                     (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE) ? "软元件" : "缓冲存储器");
    
    // 数据位列标题
    switch (g_monitor_config.form) // 显示格式
    {
        case FX_DEVMON_FORM_BIT: // 位 只需要 1 列数据位显示
            num = 1;
            break;
        case FX_DEVMON_FORM_WORD: // 位&字 只需要 8 列数据位显示
            if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type) )
            {
                num = 16; //字软元件 D,R,T,C 显示所有16位
            }else{
                //位软元件 X,Y,M,S等
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y){
                    num = 8;   //8进制 :XY  显示 8位
                }else{ 
                    num = 10;  //10进制:M,S,T,C  显示 10位
                }
            }
            break;
        case FX_DEVMON_FORM_BIT_8_10: // 位(8/10点)
            num = 8;
            break;
    }
    for (int i = 0; i < num; i++) {
        //位顺序
        if( g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_0F)  /* 0-F */
        {
            offset += sprintf(buffer + offset, "<td width=\"40\">+%X</td>", i);
        }else{ /* F-0 */
            offset += sprintf(buffer + offset, "<td width=\"40\">+%X</td>", (num-i) );
        }
    }
    // 值列标题
    offset += sprintf(buffer + offset, "\r\n<td width=\"60\">值</td>\r\n");
    // 表头行结束
    offset += sprintf(buffer + offset, "</tr>\r\n");
    // 表头结束
    offset += sprintf(buffer + offset, "</thead>\r\n");
    // 表体开始
    offset += sprintf(buffer + offset, "<tbody>\r\n");
    
    // 发送数据
    Data_Send(Dest_Sock, (uint8_t*)buffer, offset);
}

/*********************************************************************
 * @fn      FX_DEVMON_SendWebPage
 *
 * @brief   流式发送Web页面 (避免在RAM中存储完整页面)
 *
 * @param   Dest_Sock - Socket ID
 *          url - URL字符串(未使用)
 *
 * @return  none
 */
void FX_DEVMON_SendWebPage(uint8_t Sour_Sock ,uint8_t  Dest_Sock,  char *url)
{
    char *temp_buffer = HtmlBuffer;  /* 使用HtmlBuffer作为发送缓冲区 */
    char *monitor_status;
    uint32_t offset;

    /* 更新监视数据 */
    /* ★ 进入/刷新页面即发起一次 PLC 批量读（原为注释，导致从不采集）。
     * 响应到达后由 UART 分发(HTTPS.c Web_Usart_Handler)更新行数据并重发本页。 */
    FX_DEVMON_UpdateMonitor_CMD(Sour_Sock, Dest_Sock);

    /* 获取监控状态 */
    monitor_status  = (char*) HTML_GetStateString(net_monitor_state);
    /* 发送HTTP响应头 */
    SendHttpHeader(Dest_Sock, PTYPE_HTML);
    
    /* 第一次打包: HTML头部（与 CSS 拆开，以在 </head> 之前插入自动更新 meta） */
    offset = 0;
    offset += sprintf(temp_buffer + offset, HTML_GetComponent(HTML_COMP_HEADER), "软元件/缓冲存储器批量监视");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    /* 自动更新间隔：秒数取页面配置 INT(5~120)，越界钳到 5 秒。
     * 必须位于 CSS 组件之前（CSS 组件自带 </style></head>）。
     * 浏览器按此秒数重新请求本页 → 再次触发上面的批量读 → 形成自适应轮询。 */
    {
        uint16_t itv = g_monitor_config.update_interval;
        if (itv < 5u || itv > 120u) {
            itv = 5u;
        }
        offset = 0;
        offset += sprintf(temp_buffer + offset, "<meta http-equiv=\"refresh\" content=\"%u\">\r\n", itv);
        Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    }

    /* 第二次打包: CSS 样式表 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "%s", HTML_GetComponent(HTML_COMP_CSS_NEW));
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    /* 第二次打包: body开始到导航栏结束 (使用共享组件) */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "%s", HTML_GetComponent(HTML_COMP_BODY_START_NEW));
    offset += sprintf(temp_buffer + offset, "%s", HTML_GetComponent(HTML_COMP_NAV_BAR_NEW));
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第四次打包: 表单标题 - 添加居中容器 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<div style=\"margin:0 auto; width:840px; text-align:center\">\r\n");
    offset += sprintf(temp_buffer + offset, "<form action=\"fx_devmon.html\" method=\"post\" style=\"display:inline-block; text-align:left\">\r\n<font style=\"font-size=16px\"><b>软元件/缓冲存储器批量监视</b></font>\r\n<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed; font-size:14px; margin:0 auto\">\r\n<tbody>\r\n<tr>\r\n<td width=\"20\"></td><td width=\"140\"></td><td width=\"160\"></td><td width=\"80\"></td>\r\n<td width=\"100\"></td><td width=\"100\"></td><td width=\"80\"></td><td width=\"100\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第五次打包: 软元件配置行 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"5\">软元件</td>\r\n<td colspan=\"3\" align=\"right\">状态 :&nbsp;%s</td>\r\n</tr>\r\n", monitor_status);//监控状态
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"2\"><input type=\"radio\" name=\"MONT\" value=\"D\" %s>软元件名</td>\r\n", g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"3\">\r\n<select size=\"1\" name=\"DEVT\">\r\n<option %s>D</option>\r\n<option %s>R</option>\r\n<option %s>X</option>\r\n<option %s>Y</option>\r\n<option %s>M</option>\r\n<option %s>S</option>\r\n<option %s>T</option>\r\n<option %s>C</option>\r\n</select>\r\n", g_monitor_config.device_type == FX_DEVMON_DEV_D ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_R ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_X ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_Y ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_M ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_S ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_T ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_C ? "selected" : "");
    offset += sprintf(temp_buffer + offset, "<input type=\"text\" size=\"5\" maxlength=\"5\" name=\"DEVN\" value=\"%d\"></td>\r\n<td colspan=\"3\" align=\"right\"><input type=\"submit\" name=\"CMD\" value=\"监视开始\" style=\"width:120;font-weight:bold\"></td>\r\n</tr>\r\n", g_monitor_config.device_number);//监视开始按钮
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第六次打包: 缓冲存储器配置行 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"2\"><input type=\"radio\" name=\"MONT\" value=\"B\" %s>缓冲存储器</td>\r\n", g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\">模块起始 <select size=\"1\" name=\"MDL\" style=\"width:50;\">\r\n<option %s>0</option>\r\n<option %s>1</option>\r\n<option %s>2</option>\r\n<option %s>3</option>\r\n<option %s>4</option>\r\n<option %s>5</option>\r\n<option %s>6</option>\r\n<option %s>7</option>\r\n</select></td>\r\n", g_monitor_config.buffer_module == 0 ? "selected" : "", g_monitor_config.buffer_module == 1 ? "selected" : "", g_monitor_config.buffer_module == 2 ? "selected" : "", g_monitor_config.buffer_module == 3 ? "selected" : "", g_monitor_config.buffer_module == 4 ? "selected" : "", g_monitor_config.buffer_module == 5 ? "selected" : "", g_monitor_config.buffer_module == 6 ? "selected" : "", g_monitor_config.buffer_module == 7 ? "selected" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"2\">地址 <input type=\"text\" size=\"5\" maxlength=\"5\" name=\"BFMN\" value=\"%d\">\r\n<select size=\"1\" name=\"BFMV\"><option %s>10进制</option><option %s>16进制</option></select></td>\r\n", g_monitor_config.buffer_address, g_monitor_config.buffer_hex == 0 ? "selected" : "", g_monitor_config.buffer_hex == 1 ? "selected" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"3\" align=\"right\"><input type=\"submit\" name=\"CMD\" value=\"监视停止\" style=\"width:120;font-weight:bold\"></td>\r\n</tr>\r\n");//监视停止按钮
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    
    /* 第七次打包: 自动更新间隔 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"6\"></td>\r\n<td colspan=\"2\">自动更新间隔时间(5 - 120)</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\">监视格式</td><td colspan=\"1\">显示</td>\r\n<td colspan=\"1\">进制数</td><td colspan=\"2\">位顺序</td>\r\n<td colspan=\"2\"><input type=\"text\" size=\"5\" maxlength=\"3\" name=\"INT\" value=\"%d\">(秒)</td>\r\n</tr>\r\n", g_monitor_config.update_interval);
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第八次打包: 配置选项行1 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"BT\" %s>位</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_BIT ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"16\" %s>16位整数</td>\r\n", g_monitor_config.display == FX_DEVMON_DISP_16BIT ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"VAL\" value=\"D\" %s>10进制</td>\r\n", g_monitor_config.value_format == FX_DEVMON_VAL_DECIMAL ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"BITO\" value=\"0\" %s>0-F</td>\r\n", g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_0F ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"2\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第九次打包: 配置选项行2 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"WD\" %s>位＆字</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_WORD ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"32\" %s>32位整数</td>\r\n", g_monitor_config.display == FX_DEVMON_DISP_32BIT ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"VAL\" value=\"H\" %s>16进制</td>\r\n", g_monitor_config.value_format == FX_DEVMON_VAL_HEX ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"BITO\" value=\"F\" %s>F-0</td>\r\n", g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0 ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"2\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第八次打包: 配置选项行3和4 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"B10\" %s>位(8/10点)</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_BIT_8_10 ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"REAL\" %s>实数(32位)</td>\r\n<td colspan=\"5\"></td>\r\n</tr>\r\n", g_monitor_config.display == FX_DEVMON_DISP_REAL ? "checked" : "");
    offset += sprintf(temp_buffer + offset, "<tr>\r\n<td colspan=\"2\"></td><td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"ASC\" %s>ASCII字符</td>\r\n<td colspan=\"5\"></td>\r\n</tr>\r\n", g_monitor_config.display == FX_DEVMON_DISP_ASCII ? "checked" : "");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第九次打包: 分页按钮和数据表格开始 */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "</tbody></table><br>\r\n<table align=\"center\"><tbody>\r\n<tr><td><input type=\"submit\" name=\"PAGE_B\" value=\"上一页\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"上一个\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"下一个\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"下一页\" style=\"width:110;font-weight:bold\"></td>\r\n</tr></tbody></table>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第十次打包: 数据表格 - 表头和部分数据行 */
    FX_DEVMON_SendData_Table(Dest_Sock);    

    /* 第十一次打包: 数据表格 - 数据行1-5 */
    FX_DEVMON_SendDataRows(Dest_Sock, 0, 5);

    /* 第十二次打包: 数据表格 - 数据行6-10 */
    FX_DEVMON_SendDataRows(Dest_Sock, 5, 10);

    /* 第十三次打包: 数据表格 - 数据行11-15 */
    FX_DEVMON_SendDataRows(Dest_Sock, 10, 15);

    /* 第十四次打包: 数据表格 - 数据行16-20 */
    FX_DEVMON_SendDataRows(Dest_Sock, 15, 20);

    /* 第十五次打包: 数据表格 - 数据行21-25 */
    FX_DEVMON_SendDataRows(Dest_Sock, 20, 25);

    /* 第十六次打包: 数据表格 - 数据行26-30 */
    FX_DEVMON_SendDataRows(Dest_Sock, 25, 30);

    /* 第十七次打包: 数据表格 - 数据行31-32 + 结束标签和页脚 (使用公共组件) */
    offset = 0;
    offset += sprintf(temp_buffer + offset, "</tbody>\r\n</table>\r\n</div>\r\n</div>\r\n</form>\r\n</body>\r\n</html>\r\n");
    offset += sprintf(temp_buffer + offset, "%s", HTML_GetComponent(HTML_COMP_FOOTER_NEW));
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
      
    DEVMON_DEBUG("软元件监视页面流式发送完成\r\n");
}
/*********************************************************************
 * @fn      FX_DEVMON_METHOD_POST
 *
 * @brief   POST方法 处理POST请求
 * @param   Sour_Sock - Socket ID
 *          Dest_Sock - Socket ID
 *          url - 请求URL
 *
 * @return  none
 */
void FX_DEVMON_METHOD_POST(uint8_t Sour_Sock ,uint8_t  Dest_Sock,  char *http_request)
{
 
    DEVMON_DEBUG("=== 方法2: 使用Content-Length精确提取 ===\n");
    char* body_start = extract_http_body_with_content_length(http_request);
    if (body_start == NULL) {
        DEVMON_DEBUG("请求体:NULL\n");
        return;

    }
    DEVMON_DEBUG("请求体: %s\n\n", body_start);
    // 解析参数
    char *token = strtok(body_start, "&");
    while (token != NULL)
    {
        char *key = token;
        char *value = strchr(token, '=');
        if (value != NULL)
        {
            *value = '\0';
            value++;
            
            // URL解码
            char decoded_value[128] = {0};
            int i = 0, j = 0;
            while (value[i])
            {
                if (value[i] == '%')
                {
                    char hex[3] = {value[i+1], value[i+2], '\0'};
                    decoded_value[j] = (char)strtol(hex, NULL, 16);
                    i += 3;
                }
                else
                {
                    decoded_value[j] = value[i];
                    i++;
                }
                j++;
            }
            
            // 更新配置
            if (strcmp(key, "MONT") == 0)
            {
                if (strcmp(decoded_value, "D") == 0){
                    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_DEVICE;
                    DEVMON_DEBUG("监视类型:%d 使能软元件 \r\n",g_monitor_config.monitor_type);
                }
                else if (strcmp(decoded_value, "B") == 0){
                    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_BUFFER;
                    DEVMON_DEBUG("监视类型:%d 使能 缓冲存储器\r\n",g_monitor_config.monitor_type);
                }

            }
            else if (strcmp(key, "DEVT") == 0)
            {
                if (strcmp(decoded_value, "D") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_D;
                else if (strcmp(decoded_value, "R") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_R;
                else if (strcmp(decoded_value, "X") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_X;
                else if (strcmp(decoded_value, "Y") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_Y;
                else if (strcmp(decoded_value, "M") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_M;
                else if (strcmp(decoded_value, "S") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_S;
                else if (strcmp(decoded_value, "T") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_T;
                else if (strcmp(decoded_value, "C") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_C;
                DEVMON_DEBUG("软元件类型:%d \r\n",g_monitor_config.device_type);
            }
            else if (strcmp(key, "DEVN") == 0)
            {
                g_monitor_config.device_number = atoi(decoded_value);
                DEVMON_DEBUG("软元件编号:%d \r\n",g_monitor_config.device_number);
            }
            else if (strcmp(key, "MDL") == 0)
            {
                g_monitor_config.buffer_module = atoi(decoded_value);
                DEVMON_DEBUG("缓冲存储器: 模块号:%d \r\n",g_monitor_config.buffer_module);
            }
            else if (strcmp(key, "BFMN") == 0)
            {
                g_monitor_config.buffer_address = atoi(decoded_value);
                DEVMON_DEBUG("缓冲存储器: 开始地址:%d \r\n",g_monitor_config.buffer_address);
            }
            else if (strcmp(key, "BFMV") == 0)
            {
                if (strstr(decoded_value, "10") != NULL)
                    g_monitor_config.buffer_hex = 0;
                else if (strstr(decoded_value, "16") != NULL)
                    g_monitor_config.buffer_hex = 1;
                //DEVMON_DEBUG("缓冲存储器: 进制格式:%d \r\n",g_monitor_config.buffer_hex);
            }
            else if (strcmp(key, "INT") == 0)
            {
                g_monitor_config.update_interval = atoi(decoded_value);
                DEVMON_DEBUG("刷新间隔:%d 秒\r\n",g_monitor_config.update_interval);
            }
            else if (strcmp(key, "DISP") == 0)
            {
                if (strcmp(decoded_value, "16") == 0) g_monitor_config.display = FX_DEVMON_DISP_16BIT;
                else if (strcmp(decoded_value, "32") == 0) g_monitor_config.display = FX_DEVMON_DISP_32BIT;
                else if (strcmp(decoded_value, "REAL") == 0) g_monitor_config.display = FX_DEVMON_DISP_REAL;
                else if (strcmp(decoded_value, "ASC") == 0) g_monitor_config.display = FX_DEVMON_DISP_ASCII;
                DEVMON_DEBUG("显示类型:%d \r\n",g_monitor_config.display);
            }
            else if (strcmp(key, "VAL") == 0)
            {
                if (strcmp(decoded_value, "D") == 0) g_monitor_config.value_format = FX_DEVMON_VAL_DECIMAL;
                else if (strcmp(decoded_value, "H") == 0) g_monitor_config.value_format = FX_DEVMON_VAL_HEX;
                DEVMON_DEBUG("进制格式:%d \r\n",g_monitor_config.value_format);
            }
            else if (strcmp(key, "FORM") == 0)
            {
                if (strcmp(decoded_value, "BT") == 0) g_monitor_config.form = FX_DEVMON_FORM_BIT;
                else if (strcmp(decoded_value, "WD") == 0) g_monitor_config.form = FX_DEVMON_FORM_WORD;
                else if (strcmp(decoded_value, "B10") == 0) g_monitor_config.form = FX_DEVMON_FORM_BIT_8_10;
                DEVMON_DEBUG("监视格式：%d \r\n",g_monitor_config.form);
            }
            else if (strcmp(key, "BITO") == 0)
            {
                if (strcmp(decoded_value, "0") == 0) g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_0F;
                else if (strcmp(decoded_value, "F") == 0) g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_F0;
                DEVMON_DEBUG("大小端模式：%d \r\n",g_monitor_config.bit_order);
            }
            else if (strcmp(key, "CMD") == 0)
            {
                //CMD=%BC%E0%CA%D3%BF%AA%CA%BC
                if (strcmp(decoded_value, "\xBC\xE0\xCA\xD3\xBF\xAA\xCA\xBC") == 0) {
                    FX_ENETINF_SetMonitorState(FX_MONITOR_RUNNING);      //监视开始
                    DEVMON_DEBUG("监视开始按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xBC\xE0\xCA\xD3\xCD\xA3\xD6\xB9") == 0)  {
                    FX_ENETINF_SetMonitorState(FX_MONITOR_STOPPED);      //监视停止
                    DEVMON_DEBUG("监视停止按钮 \r\n");
                }
            }
            else if (strcmp(key, "PAGE_B") == 0)
            {
                //PAGE_B=%C9%CF%D2%BB%D2%B3 上一页
                //PAGE_B=%CF%C2%D2%BB%D2%B3 下一页
                //PAGE_B=%C9%CF%D2%BB%B8%F6 上一个
                //PAGE_B=%CF%C2%D2%BB%B8%F6 下一个
                if (strcmp(decoded_value, "\xC9\xCF\xD2\xBB\xD2\xB3") == 0) {
                    //上一页
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number -= FX_DEVMON_MAX_ROWS;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address -= FX_DEVMON_MAX_ROWS; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("上一页按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xCF\xC2\xD2\xBB\xD2\xB3") == 0)  {
                    //下一页
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number += FX_DEVMON_MAX_ROWS;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address += FX_DEVMON_MAX_ROWS; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("下一页按钮 \r\n");
                }
                if (strcmp(decoded_value, "\xC9\xCF\xD2\xBB\xB8\xF6") == 0) {
                    //上一个
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number -= 1;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address -= 1; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("上一个按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xCF\xC2\xD2\xBB\xB8\xF6") == 0)  {
                    //下一个
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number += 1;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address += 1; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("下一个按钮 \r\n");
                }

                if(g_monitor_config.device_number <= 0 ){
                    //软元件
                    g_monitor_config.device_number = 0;  // 软元件编号
                }else if(g_monitor_config.device_number >= 32767 ){
                    g_monitor_config.device_number = 32767; // 缓冲存储器地址
                }

                if(g_monitor_config.buffer_address <= 0 ){
                    //缓存器
                    g_monitor_config.buffer_address = 0; // 缓冲存储器地址
                }else if(g_monitor_config.buffer_address >= 4096 ){
                    g_monitor_config.buffer_address = 4096; // 缓冲存储器地址
                }
            }
        }
        token = strtok(NULL, "&");
    }
    free(body_start);      //释放内存
    DEVMON_DEBUG("释放内存 body_start \r\n" );
    // 更新监视器配置
    FX_DEVMON_UpdateMonitor_CMD(Sour_Sock, Dest_Sock);                   // 发送指令获取状态 :更新监视器配置
}
