/*********************************************************************
 * @fn      fx_devmon.h
 *
 * @brief   软元件/缓冲存储器批量监视模块头文件
 *
 * @author  Generated by AI
 * @date    2026-03-16
 *********************************************************************/

#ifndef __FX_DEVMON_H
#define __FX_DEVMON_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ch32v30x.h"

/* USER CODE END Private defines */
//#define _FX_DEVMON_DEBUG            //日志模块 开关，注释掉将关闭日志输出

#ifdef _FX_DEVMON_DEBUG
    #define DEVMON_DEBUG(format, ...)  printf (format, ##__VA_ARGS__)
#else
    #define DEVMON_DEBUG(format, ...)
#endif


/*********************************************************************
 * 宏定义
 *********************************************************************/
#define FX_DEVMON_MAX_ROWS          8       /* 最大显示行数(32→8: g_data_rows 由2432B降至384B, 回收SRAM) */
#define FX_DEVMON_DEFAULT_INTERVAL  5       /* 默认刷新间隔(秒) */
#define FX_DEVMON_MIN_INTERVAL      5       /* 最小刷新间隔 */
#define FX_DEVMON_MAX_INTERVAL      120     /* 最大刷新间隔 */

/*********************************************************************
 * 枚举类型定义
 *********************************************************************/
/* 监视类型枚举 */
typedef enum {
    FX_DEVMON_MONITOR_DEVICE = 0,           /* 软元件 */
    FX_DEVMON_MONITOR_BUFFER                /* 缓冲存储器 */
} fx_devmon_monitor_type_t;

/* 软元件类型枚举 */
typedef enum {
    FX_DEVMON_DEV_D = 0,                    /* 数据寄存器 */
    FX_DEVMON_DEV_R,                        /* 文件寄存器 */
    FX_DEVMON_DEV_X,                        /* 输入继电器 */
    FX_DEVMON_DEV_Y,                        /* 输出继电器 */
    FX_DEVMON_DEV_M,                        /* 辅助继电器 */
    FX_DEVMON_DEV_S,                        /* 状态继电器 */
    FX_DEVMON_DEV_T,                        /* 定时器 */
    FX_DEVMON_DEV_C,                        /* 计数器 */
    FX_DEVMON_DEV_TS,                       /* 定时器 触点*/
    FX_DEVMON_DEV_CS                        /* 计数器 触点*/
} fx_devmon_device_type_t;

/* 监视格式枚举 */
typedef enum {
    FX_DEVMON_FORM_BIT = 0,                 /* 位 */
    FX_DEVMON_FORM_WORD,                    /* 位&字 */
    FX_DEVMON_FORM_BIT_8_10                 /* 位(8/10点) */
} fx_devmon_form_t;

/* 显示类型枚举 */
typedef enum {
    FX_DEVMON_DISP_16BIT = 0,               /* 16位整数 */
    FX_DEVMON_DISP_32BIT,                   /* 32位整数 */
    FX_DEVMON_DISP_REAL,                    /* 实数(32位) */
    FX_DEVMON_DISP_ASCII                    /* ASCII字符 */
} fx_devmon_display_t;

/* 进制数枚举 */
typedef enum {
    FX_DEVMON_VAL_DECIMAL = 0,              /* 10进制 */
    FX_DEVMON_VAL_HEX                       /* 16进制 */
} fx_devmon_value_t;

/* 位顺序枚举 */
typedef enum {
    FX_DEVMON_BIT_ORDER_0F = 0,             /* 0-F */
    FX_DEVMON_BIT_ORDER_F0                  /* F-0 */
} fx_devmon_bit_order_t;

/* 监视状态枚举 */
typedef enum {
    FX_DEVMON_STOPPED = 0,                  /* 监视停止 */
    FX_DEVMON_RUNNING                       /* 监视运行中 */
} fx_devmon_state_t;

/*********************************************************************
 * 结构体类型定义
 *********************************************************************/
/* 监视配置结构体 */
typedef struct {
    fx_devmon_monitor_type_t monitor_type;  /* 监视类型 */
    fx_devmon_device_type_t device_type;    /* 软元件类型(缓冲存储器时无效) */
    uint16_t device_number;                 /* 软元件编号(缓冲存储器时无效) */
    uint8_t buffer_module;                  /* 缓冲存储器模块号(软元件时无效) */
    uint16_t buffer_address;                /* 缓冲存储器地址(软元件时无效) */
    uint8_t buffer_hex;                     /* 缓冲存储器地址进制:0=10进制,1=16进制 */
    fx_devmon_form_t form;                  /* 监视格式 */
    fx_devmon_display_t display;            /* 显示类型 */
    fx_devmon_value_t value_format;         /* 进制数 */
    fx_devmon_bit_order_t bit_order;        /* 位顺序 */
    uint8_t update_interval;                /* 自动更新间隔时间(秒) */
} fx_devmon_config_t;

typedef struct
{
    uint8_t b0         : 1;    
    uint8_t b1         : 1;    
    uint8_t b2         : 1;    
    uint8_t b3         : 1;    
    uint8_t b4         : 1;    
    uint8_t b5         : 1;    
    uint8_t b6         : 1;    
    uint8_t b7         : 1;     
} union_8_bit;

typedef struct
{
    uint8_t b0         : 1;
    uint8_t b1         : 1; 
    uint8_t b2         : 1; 
    uint8_t b3         : 1; 
    uint8_t b4         : 1; 
    uint8_t b5         : 1; 
    uint8_t b6         : 1; 
    uint8_t b7         : 1; 
    uint8_t b8          : 1;
    uint8_t b9          : 1;
    uint8_t b10         : 1;
    uint8_t b11         : 1;
    uint8_t b12         : 1;
    uint8_t b13         : 1;
    uint8_t b14         : 1;
    uint8_t b15         : 1;
} union_16_bit;

typedef union
{
    int16_t     s16val;      //有符号16位   
    uint16_t    u16val;      //无符号16位
    uint8_t     u8val[2];    //无符号8位
    int8_t      s8val[2];    //有符号8位
    union_16_bit u16_bit;
}fx_devmon_data_t;

/* 数据行结构体 */
typedef struct {
    uint16_t device_number;                 /* 软元件编号 */
    uint16_t bit_values[16];                /* 16个位的值 */
    uint32_t word_value;                    /* 字值 */
} fx_devmon_row_t;

/*********************************************************************
 * 函数声明
 *********************************************************************/
/* 模块初始化 */
void FX_DEVMON_Init(void);

/* 发送Web页面 (流式发送) */
void FX_DEVMON_SendWebPage(uint8_t Sour_Sock ,uint8_t  Dest_Sock,  char *url);

/* 获取监视配置 */
fx_devmon_config_t* FX_DEVMON_GetConfig(void);

/* 设置监视配置 */
void FX_DEVMON_SetConfig(fx_devmon_config_t* config);

/* 获取监视状态 */
fx_devmon_state_t FX_DEVMON_GetState(void);

/* 开始监视 */
void FX_DEVMON_StartMonitor(void);

/* 停止监视 */
void FX_DEVMON_StopMonitor(void);

/* 更新监视数据 发送指令*/
void FX_DEVMON_UpdateMonitor_CMD(uint8_t Sour_Sock ,uint8_t  Dest_Sock );

/* 更新监视数据 解析数据*/
void FX_DEVMON_UpdateMonitor_Data(u8 *buff,u16 len);

void FX_DEVMON_METHOD_POST(uint8_t Sour_Sock, uint8_t Dest_Sock, char *http_request);

/* 获取数据行 */
fx_devmon_row_t* FX_DEVMON_GetRow(uint8_t row_index);

/* 设置数据行 */
void FX_DEVMON_SetRow(uint16_t row_index );

/* 清空所有数据 */
void FX_DEVMON_ClearData(void);

#ifdef __cplusplus
}

#endif

#endif /* __FX_DEVMON_H */
