/*********************************************************************
 * @fn      fx_devmon.c
 *
 * @brief   软元件/缓冲存储器批量监视模块实现
 *
 * @author  Generated by AI
 * @date    2026-03-16
 *********************************************************************/

#include "fx_devmon.h"
#include "html_components.h"
#include <string.h>
#include <stdio.h>
#include "index.h"
#include "ethernet_app.h"
#include "melsec_fx_tables.h"   /* FX_E0_E1_Tables：软元件编号范围(eStart/eEnd)校验 */
/*********************************************************************
 * 全局变量定义
 *********************************************************************/
static fx_devmon_config_t g_monitor_config;
static fx_devmon_row_t g_data_rows[FX_DEVMON_MAX_ROWS];
static uint8_t g_row_count = 0;

/* 本次解析的状态位（页面据此给出明确提示） */
#define FX_DEVMON_NOTICE_EMPTY    0x01u /* 回帧为空 / 长度为 0 */
#define FX_DEVMON_NOTICE_TYPE     0x02u /* 显示格式与数据类别不匹配（已按 16 位整数显示） */
#define FX_DEVMON_NOTICE_UNKNOWN  0x04u /* 未知的显示格式（已按 16 位整数显示） */
#define FX_DEVMON_NOTICE_SHORT    0x08u /* 回帧长度不足（未覆盖的行显示 "--"） */
#define FX_DEVMON_NOTICE_BADDEV   0x10u /* 软元件类型/起始编号非法（暂无可监视数据） */

static uint8_t g_devmon_notice = 0;


/* ── 监视数据的字节/字序约定（与 PLC 侧一致，改动前请先看第 4 条的实测方法）──
 * 1) UART 回帧的数据段是 ASCII 十六进制文本，由 HTTPS.c 的 Web_Usart_Handler
 *    先调 hex_str_to_intlend() 解码为二进制（ASCII "12AB" → 字节 0x12,0xAB，
 *    即 buf[0]=低字节、buf[1]=高字节）。
 * 2) 16 位字： word = buf[n] | (buf[n+1] << 8)           见 ..._16BIT_form
 * 3) 32 位整数/实数：低位字在前 —— word0 = buf[0..1]、word1 = buf[2..3]，
 *    value = (word1 << 16) | word0，即
 *    (buf[3]<<24)|(buf[2]<<16)|(buf[1]<<8)|buf[0]   见 ..._32BIT/REAL_form
 *    这与三菱 FX"32 位数据低位字在 D(n)"的约定一致。
 * 4) 实测确认：PLC 侧 D100=0x5678、D101=0x1234 → 页面应显示 305419896；
 *    实数：PLC 侧 D100=0xF5C3、D101=0x4048(即 3.14f) → 页面应显示 3.14。
 */
 


/*********************************************************************
 * 静态函数声明
 *********************************************************************/
static char* FX_DEVMON_GetDeviceTypeString(fx_devmon_device_type_t dev_type);
static void    FX_DEVMON_NormalizeConfig(void);   /* 配置归一化：UpdateMonitor_CMD/SendWebPage 都在其定义之前调用 */
 
/*********************************************************************
 * @fn      FX_DEVMON_Init
 *
 * @brief   初始化监视模块
 *
 * @return  none
 */
void FX_DEVMON_Init(void)
{
    /* 初始化配置 */
    memset(&g_monitor_config, 0, sizeof(fx_devmon_config_t));
    
    /* 设置默认配置 */
    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_DEVICE;  /* 监视类型：软元件监视 */
    g_monitor_config.device_type = FX_DEVMON_DEV_D;            /* 软元件类型：数据寄存器D */
    g_monitor_config.device_number = 0;                        /* 软元件起始编号：0 */
    g_monitor_config.buffer_module = 0;                        /* 缓冲存储器模块号：0 */
    g_monitor_config.buffer_address = 0;                       /* 缓冲存储器起始地址：0 */
    g_monitor_config.buffer_hex = 0;                           /* 缓冲存储器地址格式：10进制 */
    g_monitor_config.form = FX_DEVMON_FORM_WORD;               /* 监视格式：位＆字 */
    g_monitor_config.display = FX_DEVMON_DISP_16BIT;           /* 显示格式：16位整数 */
    g_monitor_config.value_format = FX_DEVMON_VAL_DECIMAL;     /* 数值格式：10进制 */
    g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_F0;       /* 位顺序：F-0（高位在前） */
    g_monitor_config.update_interval = FX_DEVMON_DEFAULT_INTERVAL; /* 自动更新间隔：默认5秒 */
    
    /* 清空数据 */
    memset(g_data_rows, 0, sizeof(g_data_rows));
    g_row_count = 0;
 
}

// ==================== MC协议设备代码转换函数 ====================
 
/**
 * @brief 判断软元件类型是否为字软元件（支持单字写入）
 * @param device_type 软元件类型
 * @return 1-是字软元件(D,R,T,C)，0-是位软元件(X,Y,M,S等)
 */
uint8_t FX_DEVMON_IsWordDevice(uint8_t device_type)
{
    return (device_type == FX_DEVMON_DEV_D || device_type == FX_DEVMON_DEV_R ||
            device_type == FX_DEVMON_DEV_T || device_type == FX_DEVMON_DEV_C);
}

/**
 * @brief 调整C200～C234软元件点数（32位软元件）
 * @param device_type 软元件类型
 * @param start_device 起始软元件编号
 * @param device_count 原始点数
 * @return 调整后的点数
 */
uint16_t FX_DEVMON_Adjust32BitCounterCount(uint8_t device_type, uint16_t start_device, uint16_t device_count)
{
    if (device_type == FX_DEVMON_DEV_C && start_device >= 200) {
        DEVMON_DEBUG("C200～C234 32位 软元件 点数=%d\r\n", device_count);
        if (device_count % 2 == 1) {
            DEVMON_DEBUG(" 软元件点数是奇数, 错误代码57H\r\n");
        }
        return device_count * 2;
    }
    return device_count;
}

/*********************************************************************
 * @fn      FX_DEVMON_GetConfig
 *
 * @brief   获取监控配置
 *
 * @return  监控配置指针
 */
fx_devmon_config_t* FX_DEVMON_GetConfig(void)
{
    return &g_monitor_config;
}

/*********************************************************************
 * @fn      FX_DEVMON_SetConfig
 *
 * @brief   设置监控配置
 *
 * @param   config - 配置指针
 *
 * @return  none
 */
void FX_DEVMON_SetConfig(fx_devmon_config_t* config)
{
    if (config != NULL) {
        memcpy(&g_monitor_config, config, sizeof(fx_devmon_config_t));
    }
}
 
/*********************************************************************
 * @fn      FX_DEVMON_GetRow
 *
 * @brief   获取数据行
 *
 * @param   row_index - 行索引
 *
 * @return  数据行指针
 */
fx_devmon_row_t* FX_DEVMON_GetRow(uint8_t row_index)
{
    if (row_index < FX_DEVMON_MAX_ROWS) {
        return &g_data_rows[row_index];
    }
    return NULL;
}

/*********************************************************************
 * @fn      FX_DEVMON_SetRow
 *
 * @brief   设置数据行
 *
 * @param   row_index - 行索引
 * @param   row - 数据行指针
 *
 * @return  none
 */
void FX_DEVMON_SetRow(uint16_t row_index )
{   
    g_row_count = row_index;
    if ( g_row_count >= FX_DEVMON_MAX_ROWS  ) {
        g_row_count = FX_DEVMON_MAX_ROWS;
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_ClearData
 *
 * @brief   清除数据
 *
 * @return  none
 */
void FX_DEVMON_ClearData(void)
{
    memset(g_data_rows, 0, sizeof(g_data_rows));
    g_row_count = 0;
}

/*********************************************************************
 * @fn      FX_DEVMON_GetDeviceTypeString
 *
 * @brief   获取软元件类型字符串
 *
 * @param   dev_type - 软元件类型
 *
 * @return  类型字符串
 */
static char* FX_DEVMON_GetDeviceTypeString(fx_devmon_device_type_t dev_type)
{
    switch (dev_type) {
        case FX_DEVMON_DEV_D: return "D";
        case FX_DEVMON_DEV_R: return "R";
        case FX_DEVMON_DEV_X: return "X";
        case FX_DEVMON_DEV_Y: return "Y";
        case FX_DEVMON_DEV_M: return "M";
        case FX_DEVMON_DEV_S: return "S";
        case FX_DEVMON_DEV_T: return "T";
        case FX_DEVMON_DEV_C: return "C";
        default: return "D";
    }
}
 

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor
 *
 * @brief   更新监控数据
 *
 * @return  none
 */
/**
 * @brief 写缓冲存储器单个字（F1「写入外扩模块」命令）
 *   F1 帧: STX + "F1" + cmd + 地址(4B ASCII) + 长度(2B ASCII, 字节数)
 *          + 数据(每字节 2B ASCII) + ETX + 校验和；PLC 返回 ACK(0x06)/NAK(0x15)。
 *   数据按"低字节在前"发送（与 FX 缓冲存储器的字节序一致）。
 * @param Sour_Sock/Dest_Sock socket
 * @param g_address 缓冲存储器 G 地址
 * @param value     16 位字值
 * @return 0 成功，非 0 为 MELSEC_FX_ERR_* 错误码
 */
int FX_DEVMON_SetBufferWord(uint8_t Sour_Sock, uint8_t Dest_Sock, uint16_t g_address, uint16_t value)
{
    uint8_t data[2];
    uint8_t module = (uint8_t)(g_monitor_config.buffer_module % 8u);

    data[0] = (uint8_t)value;                 /* 低字节在前 */
    data[1] = (uint8_t)(value >> 8);

    return MELSEC_FX_BuildF1WriteCmd(Sour_Sock, Dest_Sock,
                                     (uint8_t)(0x30 + module),
                                     g_address, 2u, data);
}

void FX_DEVMON_UpdateMonitor_CMD(uint8_t Sour_Sock ,uint8_t  Dest_Sock )
{
 
    /* ★ 取数前归一化配置：本函数的行数与请求点数计算依赖 form / display，未归一化会出现
     *   "字软元件按位取数""位点按 32 位取数"这类长度错配（回帧长度与解析方式不一致）。 */
    FX_DEVMON_NormalizeConfig();
    g_devmon_notice &= (uint8_t)~FX_DEVMON_NOTICE_BADDEV;   /* re-evaluate device validity */

    //发送数据指令到PLC 通过网页选择的软元件/缓冲存储器起始地址和结束地址发送数据
    if( g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER)  /* 监视类型 */
    {
        /* 缓冲存储器 */
        DEVMON_DEBUG("监听 缓冲存储器:模块号=%d ",g_monitor_config.buffer_module );
        if( g_monitor_config.buffer_hex ){
            DEVMON_DEBUG("起始地址= %d \r\n", g_monitor_config.buffer_address );
        }else{
            DEVMON_DEBUG("起始地址= 0x%04X \r\n", g_monitor_config.buffer_address );
        }
        /* 行数：从起始地址最多显示 FX_DEVMON_MAX_ROWS 行，且不超过地址上限 32639 */
        {
            uint16_t rows = FX_DEVMON_MAX_ROWS;

            if (((uint32_t)g_monitor_config.buffer_address + (uint32_t)FX_DEVMON_MAX_ROWS) > 32639u) {
                rows = (uint16_t)(32639u - g_monitor_config.buffer_address);
            }
            FX_DEVMON_SetRow(rows);

            /* 取数据：缓冲存储器走 F0「读取外扩模块」命令。
             *   F0 帧: STX + "F0" + cmd + 地址(4B ASCII) + 长度(2B ASCII, 字节数) + ETX + 校验和
             *   本页一行 = 1 个字(G 地址 +1)，故字节数 = 行数 * 2
             *   (8 行 = 16 字节，远小于 uint8 上限 255，无需分批)。
             *   cmd 字段按原厂语义携带模块号('0' + U 号)；若实测该字节为子命令，
             *   改为固定 '0' 即可（模块号另议）。
             *   回应同样为 STX + ASCII 十六进制 + ETX + 校验和，由现有 UART 分发
             *   (HTTPS.c Web_Usart_Handler) 解码为二进制后交给 FX_DEVMON_UpdateMonitor_Data()。 */
            if (rows > 0u) {
                uint8_t module = (uint8_t)(g_monitor_config.buffer_module % 8u);
                (void)MELSEC_FX_BuildF0ReadCmd(Sour_Sock, Dest_Sock,
                                               (uint8_t)(0x30 + module),
                                               g_monitor_config.buffer_address,
                                               (uint8_t)(rows * 2u));
            }
        }

        
    }
    else  
    {
        uint8_t device_type = g_monitor_config.device_type;               //软元件类型

        uint16_t device_number = g_monitor_config.device_number;         //软元件编号

        uint16_t device_count = FX_DEVMON_MAX_ROWS;                       //软元件/缓冲存储器数量 

#ifdef _FX_DEVMON_DEBUG
        char *device_name = FX_DEVMON_GetDeviceTypeString(g_monitor_config.device_type);
#endif
        // 根据软元件名 解析软元件类型
       // uint8_t MC_device_type = FX_DEVMON_DeviceCodeToType(device_type);
        /* ★ 行数/请求点数按"软元件真实编号范围"裁剪。
         * 原实现 map_max_addr 恒为 0（死代码），判断永远走 else，靠 uint16 回绕 +
         * SetRow 内部钳位侥幸得到行数，"地址范围校验"实际从未生效。
         * 现从 E0/E1 映射表取该软元件类型的最大编号 eEnd(melsec_fx_tables.h)：
         *   表中无此类型 或 起始编号越界   → 不监视(0 行，页面不显示数据行)
         *   起始编号 + MAX_ROWS - 1 <= eEnd → 满行
         *   否则按剩余点数裁剪               → 同时缩短 MC 请求点数，
         *                                      避免读到 PLC 最大地址之外被回错误码
         */
        {
            uint16_t dev_end = 0;
            uint16_t rows;
            uint8_t  k;

            for (k = 0; k < TABLE_E0_E1_SIZE; k++) {
                if (FX_E0_E1_Tables[k].e_code == net_mc_meta.device_name) {
                    dev_end = FX_E0_E1_Tables[k].eEnd;
                    break;
                }
            }

            if (k >= TABLE_E0_E1_SIZE || device_number > dev_end) {
                DEVMON_DEBUG("软元件类型/起始编号非法: code=0x%04X num=%d\r\n",
                             net_mc_meta.device_name, device_number);
                rows = 0;
                g_devmon_notice |= FX_DEVMON_NOTICE_BADDEV;   /* page shows an explicit notice */
            } else if (((uint32_t)device_number + (uint32_t)FX_DEVMON_MAX_ROWS - 1u) <= (uint32_t)dev_end) {
                rows = FX_DEVMON_MAX_ROWS;
            } else {
                rows = (uint16_t)(dev_end - device_number + 1u);
            }

            FX_DEVMON_SetRow(rows);
            device_count = rows;      /* 请求点数与显示行数保持一致 */
        }
#ifdef _FX_DEVMON_DEBUG
        DEVMON_DEBUG("device_name:0x%04X\r\n", net_mc_meta.device_name);   /* 原引用已注释掉的 MC_device_type，会导致 -D_FX_DEVMON_DEBUG 编译失败 */

        DEVMON_DEBUG("监听 软元件 %s:%d \r\n",device_name,g_monitor_config.device_number );

        DEVMON_DEBUG("监视格式= %d 显示=%d 进制数=%d,位顺序=%d",
                                    g_monitor_config.form ,
                                    g_monitor_config.display ,
                                    g_monitor_config.value_format ,
                                    g_monitor_config.bit_order);
#endif
        //统一用 字单位的成批读出,只是在显示的时候不一样..
        if ( device_type == FX_DEVMON_DEV_C  ) 
        {
            if( device_number >= 200 ) 
            { 
                if( device_number + device_count > 234 )
                {
                    // 调整C200～C234 软元件点数 读取范围控制 200 -234 
                    device_count = 234 - device_number; // 起始地址 + 长度 <= 234
                } 
                // 调整C200～C234软元件点数（32位软元件）
                device_count *= 2;
            }
            else if( device_number + device_count > 200 )
            {
                // 调整C0～C199软元件点数（16位软元件）读取范围控制 0-199
                device_count = 200 - device_number; // 起始地址 + 长度 <= 199 
            }
        }

        if (device_type == FX_DEVMON_DEV_R) {
            MELSEC_FX_BuildE06ReadCmd( Sour_Sock,Dest_Sock,device_number, device_count);
        } else {
            MELSEC_FX_BuildE00ReadCmd( Sour_Sock,Dest_Sock,device_number, device_count);
        }
    }
} 

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_ASCII_form
 *
 * @brief   更新监控数据 - ASCII格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_ASCII_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows REALASCII_form \r\n" );
    /* 更新ASCII格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index < len; i++)
    {
        // 存储ASCII字符
        g_data_rows[i].word_value = 0;
        if (buff_index + 1 < len) {
            // 存储两个ASCII字符到一个16位值中
            g_data_rows[i].word_value = (buff[buff_index] << 8) | buff[buff_index + 1];
            buff_index += 2;
            DEVMON_DEBUG("%X\r\n",g_data_rows[i].word_value );
        }
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        
        // 计算位值
        DEVMON_DEBUG("bit_[%d]:",i  );
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_REAL_form
 *
 * @brief   更新监控数据 - 实数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_REAL_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows REAL_form \r\n" );
    /* 更新实数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 3 < len; i++)
    {
        // 存储32位实数
        union {
            float f;
            uint32_t u;
        } real_value;
        
        real_value.u = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                      (buff[buff_index+1] << 8) | buff[buff_index];
        DEVMON_DEBUG("%f\r\n",real_value.f );
        // 将实数转换为整数存储（实际应用中可能需要调整）
        /* 保存浮点的"原始位模式"而不是截断后的整数（原写法把 3.14 显示成 3）。
         * 页面按 float 解释该 32 位值；字序约定见文件开头说明。 */
        g_data_rows[i].word_value = real_value.u;
        buff_index += 4;
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_32BIT_form
 *
 * @brief   更新监控数据 - 32位整数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_32BIT_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    
    DEVMON_DEBUG("g_data_rows 32BIT_form \r\n" );
    /* 更新32位整数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 3 < len; i++)
    {
        // 存储32位整数
        g_data_rows[i].word_value = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                                   (buff[buff_index+1] << 8) | buff[buff_index];
        buff_index += 4;
        DEVMON_DEBUG("%X\r\n",g_data_rows[i].word_value );
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;

        DEVMON_DEBUG("bit_[%d]:",i  );
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_UpdateMonitor_Data_16BIT_form
 *
 * @brief   更新监控数据 - 16位整数格式
 *
 * @param   device_type - 设备类型
 * @param   buff - 数据缓冲区
 * @param   len - 数据长度
 *
 * @return  none
 */
void FX_DEVMON_UpdateMonitor_Data_16BIT_form(u8 device_type, u8 *buff, u16 len)
{
    u8 device_number = g_monitor_config.device_number;
    u16 buff_index = 0;
    DEVMON_DEBUG("g_data_rows 16BIT_form \r\n" );
    /* 更新16位整数格式数据 */
    for (int i = 0; i < FX_DEVMON_MAX_ROWS && buff_index + 1 < len; i++)
    {
        // 字单位的成批读出
        if (device_type == FX_DEVMON_DEV_C && device_number >= 200)
        {
            // C200～C234 (32位软元件)
            if (buff_index + 3 < len) {
                g_data_rows[i].word_value = (buff[buff_index+3] << 24) | (buff[buff_index+2] << 16) | 
                                           (buff[buff_index+1] << 8) | buff[buff_index];
                buff_index += 4;
                DEVMON_DEBUG(" %X ", g_data_rows[i].word_value );
            }
        }
        else
        {
            // 16位软元件
            g_data_rows[i].word_value = (buff[buff_index+1] << 8) | buff[buff_index];
            buff_index += 2;
            DEVMON_DEBUG(" %X ", g_data_rows[i].word_value );
        }
        
        // 设置软元件编号
        g_data_rows[i].device_number = device_number + i;
        DEVMON_DEBUG("bit_[%d]:",i  );
        // 计算位值
        for (uint8_t bit_index = 0; bit_index < 16; bit_index++) {
            g_data_rows[i].bit_values[bit_index] = (g_data_rows[i].word_value >> bit_index) & 0x01;
            DEVMON_DEBUG(" %X -", g_data_rows[i].bit_values[bit_index] );
        }
        DEVMON_DEBUG("\r\n");
    }
}

/* ══════════════════════════════════════════════════════════════════
 * ★ 串口回应数据的"类型判定 + 类型化解析显示"（本次增强）
 *
 * 一、数据类别 kind 由"监视类型 + 软元件类型"唯一决定，与显示格式无关：
 *     缓冲存储器 / D R T C     -> 字类型 FX_DEVMON_KIND_WORD
 *     X Y M S（含 TS/CS 触点） -> 位类型 FX_DEVMON_KIND_BIT
 *     其它取值                 -> 非法   FX_DEVMON_KIND_NONE
 *
 * 二、"数据类别"与"显示格式"的匹配关系（不匹配 -> 默认转换为 16 位整数 + 页面明确提示）：
 *     字类型：16 位整数 / 32 位整数 / 实数 / ASCII 字符 均合法
 *     位类型：仅 16 位整数合法（位点没有 32 位整数、实数、ASCII 的概念）
 *
 * 三、每行占用的字节数（回帧长度校验用，与各 *_form 解析函数一致）：
 *     16 位整数 / ASCII -> 2 字节；32 位整数 / 实数 -> 4 字节
 *     C200~C234（32 位计数器）在 16 位整数格式下同样按 4 字节消费
 *
 * 四、边界处理：回帧长度不足的行标为无效(is_valid=0)、值列显示 "--"，
 *     不再显示上一轮的残留值；空回帧、非法软元件也各有明确提示。
 * ══════════════════════════════════════════════════════════════════ */

#define FX_DEVMON_KIND_NONE   0u        /* 非法 / 未知 */
#define FX_DEVMON_KIND_WORD   1u        /* 字类型 */
#define FX_DEVMON_KIND_BIT    2u        /* 位类型 */


/* 判定"数据类别"—— 类型判定的唯一入口 */
static uint8_t FX_DEVMON_GetDataKind(void)
{
    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER) {
        return FX_DEVMON_KIND_WORD;                 /* 缓冲存储器：按字处理 */
    }
    if (FX_DEVMON_IsWordDevice((uint8_t)g_monitor_config.device_type)) {
        return FX_DEVMON_KIND_WORD;                 /* D / R / T / C */
    }
    if ((uint8_t)g_monitor_config.device_type <= (uint8_t)FX_DEVMON_DEV_CS) {
        return FX_DEVMON_KIND_BIT;                  /* X / Y / M / S / TS / CS */
    }
    return FX_DEVMON_KIND_NONE;
}

/* 一行数据占用几个字节（与各解析函数内部一致） */
static uint8_t FX_DEVMON_BytesPerRow(uint8_t display)
{
    if (display == FX_DEVMON_DISP_32BIT || display == FX_DEVMON_DISP_REAL) {
        return 4;                                   /* 32 位：两个字 */
    }
    if (display == FX_DEVMON_DISP_16BIT &&
        g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE &&
        g_monitor_config.device_type == FX_DEVMON_DEV_C &&
        g_monitor_config.device_number >= 200u) {
        return 4;                                   /* C200~C234：32 位计数器 */
    }
    return 2;                                       /* 16 位整数 / ASCII：一个字 */
}

/* 该显示格式是否与数据类别匹配（类型不匹配的判定） */
static uint8_t FX_DEVMON_IsDisplayValid(uint8_t kind, uint8_t display)
{
    if (display > (uint8_t)FX_DEVMON_DISP_ASCII) {
        return 0;                                   /* 未知格式 */
    }
    if (kind == FX_DEVMON_KIND_BIT) {
        return (display == (uint8_t)FX_DEVMON_DISP_16BIT) ? 1u : 0u;
    }
    if (kind == FX_DEVMON_KIND_WORD) {
        return 1u;
    }
    return (display == (uint8_t)FX_DEVMON_DISP_16BIT) ? 1u : 0u;
}

/* 该行数据是否有效（本轮回帧是否覆盖到该行） */
static uint8_t FX_DEVMON_RowIsValid(uint16_t row)
{
    if (row >= (uint16_t)FX_DEVMON_MAX_ROWS) {
        return 0;
    }
    return g_data_rows[row].is_valid ? 1u : 0u;
}

/* 实数(32 位浮点)的定点显示：±整数.三位小数
 * 不使用 printf 的 %f（会拉入完整浮点 printf），只做最基本的浮点运算。 */
static void FX_DEVMON_FormatReal(uint32_t bits, char *out)
{
    union { float f; uint32_t u; } rv;
    int32_t  ip;
    uint32_t frac;
    const char *sign = "";

    rv.u = bits;
    if (rv.f != rv.f) {                             /* NaN */
        out[0] = 'N'; out[1] = 'a'; out[2] = 'N'; out[3] = 0;
        return;
    }
    if (rv.f < 0.0f) {
        sign = "-";
        rv.f = -rv.f;
    }
    if (rv.f > 2000000000.0f) {                     /* 超出定点表示范围 */
        out[0] = 'O'; out[1] = 'V'; out[2] = 'F'; out[3] = 0;
        return;
    }
    ip   = (int32_t)rv.f;
    frac = (uint32_t)((rv.f - (float)ip) * 1000.0f + 0.5f);
    if (frac >= 1000u) {
        frac = 0u;
        ip  += 1;
    }
    sprintf(out, "%s%d.%03u", sign, (int)ip, (unsigned)frac);
}

/* ★ 值列的"类型化"格式化：数据行值列的唯一出口
 *   行无效       -> "--"            （本轮回帧未覆盖，明确表示"无数据"）
 *   位类型       -> "0" / "1"       （位点不按整数/32 位显示）
 *   ASCII 字符   -> 两个可打印字符  （不可打印显示 '.'；原实现把 ASCII 当数字显示）
 *   实数(32位)   -> ±整数.三位小数  （原实现显示的是 IEEE754 位模式整数）
 *   32 位整数    -> 16 进制 %08X / 10 进制
 *   16 位整数    -> 16 进制 %04X / 10 进制
 * out 缓冲由调用方保证不小于 12 字节。 */
static void FX_DEVMON_FormatValueCell(uint16_t row, char *out, uint8_t out_size)
{
    uint32_t v;
    char     hi;
    char     lo;

    if (out == NULL || out_size < 12u) {
        return;
    }
    out[0] = 0;

    if (!FX_DEVMON_RowIsValid(row)) {
        out[0] = '-';
        out[1] = '-';
        out[2] = 0;
        return;
    }

    v = g_data_rows[row].word_value;

    /* 位类型：值只有 0 / 1（体现"位型"与"字型"的显示差异） */
    if (FX_DEVMON_GetDataKind() == FX_DEVMON_KIND_BIT) {
        sprintf(out, "%u", (unsigned)(g_data_rows[row].bit_values[0] ? 1u : 0u));
        return;
    }

    switch (g_monitor_config.display) {
    case FX_DEVMON_DISP_ASCII:                      /* 字符型 */
        hi = (char)((v >> 8) & 0xFFu);
        lo = (char)(v & 0xFFu);
        if ((uint8_t)hi < 0x20u || (uint8_t)hi > 0x7Eu) {
            hi = '.';
        }
        if ((uint8_t)lo < 0x20u || (uint8_t)lo > 0x7Eu) {
            lo = '.';
        }
        out[0] = hi;
        out[1] = lo;
        out[2] = 0;
        break;

    case FX_DEVMON_DISP_REAL:                       /* 实数(32位) */
        FX_DEVMON_FormatReal(v, out);
        break;

    case FX_DEVMON_DISP_32BIT:                      /* 32 位整数 */
        if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
            sprintf(out, "%08X", (unsigned)v);
        } else {
            sprintf(out, "%d", (int)v);
        }
        break;

    default:                                        /* 16 位整数 */
        if (g_monitor_config.value_format == FX_DEVMON_VAL_HEX) {
            sprintf(out, "%04X", (unsigned)(v & 0xFFFFu));
        } else {
            sprintf(out, "%d", (int)v);
        }
        break;
    }
}

/* 值列的样式类：位类型的"1"沿用现有 bit1 样式，其余不加样式 */
static const char *FX_DEVMON_ValueCellClass(uint16_t row)
{
    if (FX_DEVMON_GetDataKind() == FX_DEVMON_KIND_BIT &&
        FX_DEVMON_RowIsValid(row) &&
        g_data_rows[row].bit_values[0] != 0u) {
        return "bit1";
    }
    return "";
}

/* ★ 表格上方的"类型说明 + 异常提示"（体现类型差异、并给出明确提示）
 *   正常：显示一行 数据类别 / 显示格式 / 行数 / 每行字节数
 *   异常：追加一行红字说明（类型不匹配、回帧不足、空数据、非法软元件） */
static void FX_DEVMON_SendDataNotice(uint8_t Dest_Sock)
{
    char    *buffer = HtmlBuffer;
    uint32_t offset = 0;
    uint8_t  kind   = FX_DEVMON_GetDataKind();
    const char *kind_str;
    const char *disp_str;

    if (kind == FX_DEVMON_KIND_BIT) {
        kind_str = "位类型软元件(X/Y/M/S)";
    } else if (kind == FX_DEVMON_KIND_WORD) {
        kind_str = (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER)
                   ? "字类型(缓冲存储器)" : "字类型软元件(D/R/T/C)";
    } else {
        kind_str = "未知类型";
    }

    switch (g_monitor_config.display) {
    case FX_DEVMON_DISP_32BIT: disp_str = "32位整数";     break;
    case FX_DEVMON_DISP_REAL:  disp_str = "实数(32位)";   break;
    case FX_DEVMON_DISP_ASCII: disp_str = "ASCII字符";    break;
    default:                   disp_str = "16位整数";     break;
    }

    offset += HTML_PACK(buffer, offset, "<div style=\"width:840px;margin:4px auto;font-size:12px;color:#333\">");
    offset += HTML_PACK(buffer, offset, "数据类别：%s ｜ 值解析方式：%s ｜ 一页 %u 行 ｜ 每行 %u 字节",
                        kind_str, disp_str,
                        (unsigned)g_row_count,
                        (unsigned)FX_DEVMON_BytesPerRow((uint8_t)g_monitor_config.display));
    offset += HTML_PACK(buffer, offset, "</div>");
    Data_Send(Dest_Sock, (uint8_t*)buffer, offset);

    if (g_devmon_notice != 0u) {
        offset = 0;
        offset += HTML_PACK(buffer, offset, "<div style=\"width:840px;margin:4px auto;font-size:12px;color:#c00000\">注意：");
        if (g_devmon_notice & FX_DEVMON_NOTICE_BADDEV) {
            offset += HTML_PACK(buffer, offset, "软元件类型或起始编号超出范围，暂无可监视数据；");
        }
        if (g_devmon_notice & FX_DEVMON_NOTICE_EMPTY) {
            offset += HTML_PACK(buffer, offset, "未收到有效数据（回帧为空）；");
        }
        if (g_devmon_notice & FX_DEVMON_NOTICE_TYPE) {
            offset += HTML_PACK(buffer, offset, "显示格式与数据类别不匹配，已按 16 位整数显示；");
        }
        if (g_devmon_notice & FX_DEVMON_NOTICE_UNKNOWN) {
            offset += HTML_PACK(buffer, offset, "未知的显示格式，已按 16 位整数显示；");
        }
        if (g_devmon_notice & FX_DEVMON_NOTICE_SHORT) {
            offset += HTML_PACK(buffer, offset, "本轮回帧长度不足，未覆盖的行显示为 --；");
        }
        offset += HTML_PACK(buffer, offset, "</div>");
        Data_Send(Dest_Sock, (uint8_t*)buffer, offset);
    }
}

/* 表格布局视角下是否按"字(16 位)"展开：
 *   缓冲存储器：不涉及软元件类型，每行固定 1 个字 -> 按 16 位展开
 *   软元件    ：D/R/T/C 是字软元件 -> 按 16 位展开；X/Y/M/S 为位软元件 */
void FX_DEVMON_UpdateMonitor_Data(u8 *buff, u16 len)
{
    uint8_t  kind;
    uint8_t  display;
    uint8_t  bytes_per_row;
    uint16_t rows_ok;
    uint16_t valid_rows;
    uint16_t i;

    /* ★ 本次解析的状态清零（保留"软元件非法"——它由取数前的配置判定设置，
     *   不随回帧变化）。下面按实际情况重新置位，页面据它给出明确提示。 */
    g_devmon_notice &= (uint8_t)~FX_DEVMON_NOTICE_BADDEV;

    /* ① 判定数据类别：字类型 / 位类型 / 非法 —— 类型判定的唯一入口 */
    kind = FX_DEVMON_GetDataKind();
    if (kind == FX_DEVMON_KIND_NONE) {
        DEVMON_DEBUG("数据类别非法: monitor_type=%d device_type=%d\r\n",
                     g_monitor_config.monitor_type, g_monitor_config.device_type);
        g_devmon_notice |= FX_DEVMON_NOTICE_TYPE;
        for (i = 0; i < (uint16_t)FX_DEVMON_MAX_ROWS; i++) {
            g_data_rows[i].is_valid = 0;
        }
        return;
    }

    /* ② 缓冲区与长度边界检查 */
    if (buff == NULL || len == 0u) {
        DEVMON_DEBUG("数据缓冲区为空\r\n");
        g_devmon_notice |= FX_DEVMON_NOTICE_EMPTY;
        for (i = 0; i < (uint16_t)FX_DEVMON_MAX_ROWS; i++) {
            g_data_rows[i].is_valid = 0;
        }
        return;
    }

    /* ③ 显示格式与数据类别匹配检查：不匹配 -> 默认转换为 16 位整数 + 记录提示 */
    display = (uint8_t)g_monitor_config.display;
    if (display > (uint8_t)FX_DEVMON_DISP_ASCII) {
        DEVMON_DEBUG("未知的显示格式: %d\r\n", display);
        g_devmon_notice |= FX_DEVMON_NOTICE_UNKNOWN;
    } else if (!FX_DEVMON_IsDisplayValid(kind, display)) {
        DEVMON_DEBUG("显示格式与数据类别不匹配: kind=%d display=%d -> 16BIT\r\n", kind, display);
        g_devmon_notice |= FX_DEVMON_NOTICE_TYPE;
    } else {
        DEVMON_DEBUG("显示格式与数据类别匹配: kind=%d display=%d\r\n", kind, display);
    }
    if (g_devmon_notice & (FX_DEVMON_NOTICE_TYPE | FX_DEVMON_NOTICE_UNKNOWN)) {
        display = (uint8_t)FX_DEVMON_DISP_16BIT;    /* 默认转换 */
        g_monitor_config.display = FX_DEVMON_DISP_16BIT;   /* 写回：页面单选显示实际生效值 */
    }

    /* ④ 回帧长度校验（边界）：本轮回帧能给几行"完整"数据 */
    bytes_per_row = FX_DEVMON_BytesPerRow(display);
    rows_ok = (uint16_t)(len / bytes_per_row);
    if (rows_ok > (uint16_t)FX_DEVMON_MAX_ROWS) {
        rows_ok = (uint16_t)FX_DEVMON_MAX_ROWS;
    }

    DEVMON_DEBUG("监视格式=%d 显示=%d 进制数=%d 位顺序=%d kind=%d len=%d 每行=%d字节\r\n",
                 g_monitor_config.form,
                 display,
                 g_monitor_config.value_format,
                 g_monitor_config.bit_order,
                 kind, len, bytes_per_row);

    /* ⑤ 分派：按"数据类别 + 显示格式"调用对应解析函数
     *    （各解析函数内部还会区分 16 位软元件 / C200~C234 32 位计数器） */
    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER) {
        /* 缓冲存储器：F0 指令，按字取数 */
        FX_DEVMON_UpdateMonitor_Data_16BIT_form((u8)g_monitor_config.device_type, buff, len);
    } else {
        switch (display) {
        case FX_DEVMON_DISP_32BIT:
            FX_DEVMON_UpdateMonitor_Data_32BIT_form((u8)g_monitor_config.device_type, buff, len);
            break;

        case FX_DEVMON_DISP_REAL:
            FX_DEVMON_UpdateMonitor_Data_REAL_form((u8)g_monitor_config.device_type, buff, len);
            break;

        case FX_DEVMON_DISP_ASCII:
            FX_DEVMON_UpdateMonitor_Data_ASCII_form((u8)g_monitor_config.device_type, buff, len);
            break;

        case FX_DEVMON_DISP_16BIT:
        default:
            FX_DEVMON_UpdateMonitor_Data_16BIT_form((u8)g_monitor_config.device_type, buff, len);
            break;
        }
    }

    /* ⑥ 标注每一行的有效性：本轮回帧覆盖到的行有效，其余无效
     *    （值列对无效行显示 "--"，避免把上一轮的残留值当成当前值） */
    valid_rows = (rows_ok < g_row_count) ? rows_ok : g_row_count;
    for (i = 0; i < (uint16_t)FX_DEVMON_MAX_ROWS; i++) {
        g_data_rows[i].is_valid = (i < valid_rows) ? 1u : 0u;
    }
    if (valid_rows < g_row_count) {
        DEVMON_DEBUG("回帧长度不足: len=%d 需要=%d 字节\r\n",
                     len, (int)((uint32_t)g_row_count * bytes_per_row));
        g_devmon_notice |= FX_DEVMON_NOTICE_SHORT;
    }
}

static uint8_t FX_DEVMON_LayoutIsWord(void)
{
    uint8_t dev = (uint8_t)g_monitor_config.device_type;

    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER) {
        return 1;
    }
    return FX_DEVMON_IsWordDevice(dev);
}

/* ★ 配置归一化（页面渲染 / 发起取数之前统一调用一次，幂等）
 *
 * 目的：把"软元件类别"与"监视格式 form / 显示格式 display"这几项互斥的选项
 *       收敛到合法组合，避免出现"字软元件按位显示""位的数值按 32 位整数显示"
 *       这类无意义（甚至会把数据读错/显示错）的组合。
 *
 * 判断先后顺序（即本函数的执行次序）：
 *   1) 先按"监视类型"分流：缓冲存储器 / 软元件
 *        缓冲存储器 -> 本页每行固定取 1 个字、按 16 位展开：
 *                       form 固定为 位＆字，display 固定为 16 位整数；
 *   2) 软元件再按"是否字软元件"分类（D/R/T/C 为字；X/Y/M/S 为位）：
 *        字软元件 -> form 固定为 位＆字：一个字里 16 个位并列显示。
 *                    不允许退化成"一行一个位"的位格式 —— 本页一页只有
 *                    FX_DEVMON_MAX_ROWS 行，位格式下 8 行只能看到 D0 的 8 个位，
 *                    与"批量监视"的语义不符；display 保留用户选择(16/32/实数/ASCII)。
 *        位软元件 -> display 固定为 16 位整数：位点只有 0/1，32 位整数/实数/
 *                    ASCII 对它没有意义；form 保留用户选择(位 / 位＆字 / 位(8/10点))。
 *
 * 注意：归一化会写回 g_monitor_config，因此页面上的单选按钮会显示"实际生效"的
 *       选项（例如给 X 选了 32 位，重绘后会回到 16 位），这是有意为之。
 */
static void FX_DEVMON_NormalizeConfig(void)
{
    uint8_t is_word;

    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER) {
        /* 缓冲存储器：每行 1 个字，按 16 位展开 */
        g_monitor_config.form    = FX_DEVMON_FORM_WORD;
        g_monitor_config.display = FX_DEVMON_DISP_16BIT;
        return;
    }

    is_word = FX_DEVMON_IsWordDevice((uint8_t)g_monitor_config.device_type);

    if (is_word) {
        /* 字软元件 D/R/T/C：禁止按位显示 */
        g_monitor_config.form = FX_DEVMON_FORM_WORD;
    } else {
        /* 位软元件 X/Y/M/S：数值只有 0/1，显示类型固定 16 位整数 */
        g_monitor_config.display = FX_DEVMON_DISP_16BIT;
    }
}

/* ★ 当前配置下"一行里有几个位(BIT)列"
 * 表头、数据行、空行三处必须用同一个来源，否则列数不一致会导致表格错位
 * （原实现三处各写一套 switch：空行里"位＆字"恒为 8 列，而字软元件数据行是 16 列，
 *   于是空行比数据行窄一半）。
 * 说明：调用前应已执行 FX_DEVMON_NormalizeConfig()。
 */
static uint8_t FX_DEVMON_BitColumnCount(void)
{
    switch (g_monitor_config.form) {
    case FX_DEVMON_FORM_BIT:              /* 位：一行一个点 */
        return 1;
    case FX_DEVMON_FORM_BIT_8_10:         /* 位(8/10点)：一行 8 点 */
        return 8;
    default:                              /* 位＆字 */
        if (FX_DEVMON_LayoutIsWord()) {
            return 16;                    /* D/R/T/C 与缓冲存储器：一个字 16 位 */
        }
        if (g_monitor_config.device_type == FX_DEVMON_DEV_X ||
            g_monitor_config.device_type == FX_DEVMON_DEV_Y) {
            return 8;                     /* X/Y：8 进制软元件，显示 8 位 */
        }
        return 10;                        /* M/S 等：显示 10 位 */
    }
}

/*********************************************************************
 * @fn      FX_DEVMON_SendData_Table_Name
 *
 * @brief   生成第 index 行的"软元件名称"（类型前缀 + 编号）
 *
 * @param   dev_name - 输出缓冲
 *          index    - 行索引
 *
 * @return  名称长度
 */
static uint16_t FX_DEVMON_SendData_Table_Name(char * dev_name , uint16_t index)
{
    uint16_t offset = 0;
    if (dev_name == NULL ) return 0;
    /* 行头 名称 */
    if (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE) 
    {
        /* 软元件 名称 */
        /* 取类型前缀(D/R/X/Y/M/S/T/C)的长度作为偏移：下面用 dev_name + offset 追加编号。
         * 原实现丢弃了 sprintf 的返回值(offset 恒为 0)，编号从 dev_name[0] 开始写，
         * 把刚写好的类型前缀覆盖掉 -> 页面"软元件"列只剩编号(如 4/7)而没有 D4/D7。 */
        offset = (uint16_t)sprintf(dev_name, "%s", FX_DEVMON_GetDeviceTypeString(g_monitor_config.device_type));
        /* ★ 编号格式的判断顺序（配置已在 FX_DEVMON_NormalizeConfig() 中归一化）：
         *   ① 先分"字软元件 / 位软元件"；
         *   ② 字软元件：form 已固定为"位＆字"，一行一个软元件，编号 = 起址 + index；
         *      位软元件：再分"位 / 位＆字"（一行一个点，编号 = 起址 + index）
         *                与"位(8/10点)"（一行一组点，编号按组起点递增，沿用原口径）；
         *   ③ X/Y 是 8 进制软元件，统一按 3 位 8 进制显示；其余按 10 进制。
         * 原实现把"位"与"位＆字"两套完全相同的逻辑各写了一遍，这里合并为一处。 */
        if (FX_DEVMON_IsWordDevice(g_monitor_config.device_type))
        {
            /* 字软元件 D/R/T/C：D0、D1 …（一行一个软元件） */
            offset += sprintf(dev_name + offset, "%d", g_monitor_config.device_number + index);
        }
        else if (g_monitor_config.form == FX_DEVMON_FORM_BIT_8_10)
        {
            /* 位(8/10点)：一行一组点，编号按组起点递增（沿用原实现口径） */
            if (g_monitor_config.device_type == FX_DEVMON_DEV_X ||
                g_monitor_config.device_type == FX_DEVMON_DEV_Y) {
                offset += sprintf(dev_name + offset, "%d", g_monitor_config.device_number + index*200);
            } else {
                offset += sprintf(dev_name + offset, "%d", g_monitor_config.device_number + index*8*10);
            }
        }
        else
        {
            /* 位 / 位＆字：一行一个点（或一个软元件） */
            if (g_monitor_config.device_type == FX_DEVMON_DEV_X ||
                g_monitor_config.device_type == FX_DEVMON_DEV_Y) {
                offset += sprintf(dev_name + offset, "%03o", (unsigned)(g_monitor_config.device_number + index));
            } else {
                offset += sprintf(dev_name + offset, "%d", g_monitor_config.device_number + index);
            }
        }
                
    } else {
        /* 缓冲存储器 名称*/
        sprintf(dev_name, "U%d\\G%d", g_monitor_config.buffer_module,g_monitor_config.buffer_address + index);
    }

    return strlen( dev_name );
}

/*********************************************************************
 * @fn      FX_DEVMON_SendDataRows
 *
 * @brief   发送数据行到指定范围
 *
 * @param   Dest_Sock - Socket ID
 *          start_row - 起始行索引
 *          end_row - 结束行索引
 *
 * @return  none
*/
static void FX_DEVMON_SendDataRows(uint8_t Dest_Sock, int start_row, int end_row)
{
    char *temp_buffer = HtmlBuffer;
    char dev_name[32];
    char value_text[16];                    /* value cell buffer (see FX_DEVMON_FormatValueCell) */

    uint32_t offset;
    int i, j;
    
    offset = 0;
    DEVMON_DEBUG(" SendDataRows START:%d-END:%d\n",start_row,end_row);
    for (i = start_row; i < end_row && i < g_row_count; i++) 
    {
        // 软元件名称.
        FX_DEVMON_SendData_Table_Name ( dev_name, i );
        DEVMON_DEBUG("name:%s\n",dev_name);
       // 开始拼接 HTML 代码
        /* ★ 不要在这里清零 offset：该缓冲是"多行累积、接近阈值才整批发送"的，
         *   原实现每行开头 offset = 0，导致上一行的内容被本行覆盖，
         *   结果每段只有最后一行发得出去(现场表现为表格只剩 D4、D7 两行)。 */
        offset += HTML_PACK(temp_buffer, offset, "<tr>");
        /* 软元件名称 */    
        offset += HTML_PACK(temp_buffer, offset, "<td>%s</td>", dev_name);

        /* 监视格式 */
        switch (g_monitor_config.form)
        {
        case FX_DEVMON_FORM_BIT:   /* 位 */
        
            // 只显示第0位
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[0] ? "bit1" : "c0", g_data_rows[i].bit_values[0]);
            /* value cell: typed formatting (-- when invalid, 0/1 for bit kinds, chars for ASCII, real for REAL) */
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
            break;
            

        case FX_DEVMON_FORM_WORD:        /* 位&字 */
            // 显示所有16位
            if (FX_DEVMON_LayoutIsWord() )
            {
                //字软元件 D,R,T,C
                if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                    for (j = 0; j < 16; j++) {
                        offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[15 - j] ? "bit1" : "c0", g_data_rows[i].bit_values[15 - j]);
                    }
                } else {
                    /* 0-F 顺序 */
                    for (j = 0; j < 16; j++) {
                        offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[j] ? "bit1" : "c0", g_data_rows[i].bit_values[j]);
                    }
                }
                // 数值
                /* value cell: typed formatting (-- when invalid, 0/1 for bit kinds, chars for ASCII, real for REAL) */
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
                
            }else{
                if(g_monitor_config.device_type == FX_DEVMON_DEV_X || g_monitor_config.device_type == FX_DEVMON_DEV_Y)
                {
                    //8进制XY 
                   if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                        for (j = 0; j < 8; j++) {
                            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[8 - j] ? "bit1" : "c0", g_data_rows[i].bit_values[8 - j]);
                        }
                    } else {
                        /* 0-F 顺序 */
                        for (j = 0; j < 8; j++) {
                            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[j] ? "bit1" : "c0", g_data_rows[i].bit_values[j]);
                        }
                    }
                    // 数值 8位
                    /* value cell: typed formatting (-- when invalid, 0/1 for bit kinds, chars for ASCII, real for REAL) */
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
                }else{ 
                    //M,S,T,C 10进制
                     if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                    /* F-0 顺序 */
                        for (j = 0; j < 10; j++) {
                            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[10 - j] ? "bit1" : "c0", g_data_rows[i].bit_values[10 - j]);
                        }
                    } else {
                        /* 0-F 顺序 */
                        for (j = 0; j < 10; j++) {
                            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[j] ? "bit1" : "c0", g_data_rows[i].bit_values[j]);
                        }
                    }
                    // 数值10位
                    /* value cell: typed formatting (-- when invalid, 0/1 for bit kinds, chars for ASCII, real for REAL) */
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
                }
            }
            break;
        case FX_DEVMON_FORM_BIT_8_10:    /* 位(8/10点) */
            /* 该分支一次要用 i..i+7 共 8 行，且下面还引用 8-i；
             * 若行数不足(i 不为 0)会访问到 g_data_rows 之外(数组仅 FX_DEVMON_MAX_ROWS 行)。 */
            if (i + 7 >= (int)FX_DEVMON_MAX_ROWS) {
                break;
            }
            //字软元件 D,R,T,C 每一个位都显示16位数据
            if (g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0) {
                /* F-0 顺序 */
                for (j = 0; j < 8; j++) {
                    offset += HTML_PACK(temp_buffer, offset, "<td class=\"c0\">%d</td>", g_data_rows[(8 - i) < FX_DEVMON_MAX_ROWS ? (8 - i) : 0].word_value);
                }
            } else {
                /* 0-F 顺序 */
                for (j = 0; j < 16; j++) {
                    offset += HTML_PACK(temp_buffer, offset, "<td class=\"c0\">%d</td>", g_data_rows[i].word_value);
                }
            }
            // 数值
            /* value cell: typed formatting (-- when invalid, 0/1 for bit kinds, chars for ASCII, real for REAL) */
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
            i += 8;

            break;
            
        default:
            // 默认情况，显示所有16位和数值
            for (j = 0; j < 16; j++) {
                offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%d</td>", g_data_rows[i].bit_values[j] ? "bit1" : "c0", g_data_rows[i].bit_values[j]);
            }
            FX_DEVMON_FormatValueCell((uint16_t)i, value_text, (uint8_t)sizeof(value_text));
            offset += HTML_PACK(temp_buffer, offset, "<td class=\"%s\">%s</td>\r\n", FX_DEVMON_ValueCellClass((uint16_t)i), value_text);
            break;
        }
        /* 注释 */
        offset += HTML_PACK(temp_buffer, offset, "</tr>\r\n");

        /* 数据量达到阈值时发送 */
        if (offset > 450) {
            Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
            offset = 0;
        }
    }
    
    /* 空行处理 */
    for (i = (g_row_count > start_row ? g_row_count : start_row); i < end_row && i < FX_DEVMON_MAX_ROWS; i++)
    {
        offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n");
        offset += HTML_PACK(temp_buffer, offset, "<td>&nbsp;</td>\r\n");
        
        /* 空行列数必须与数据行列数完全一致（共用 FX_DEVMON_BitColumnCount()），
         * 否则空行比数据行窄/宽，表格会错位。 */
        for (j = 0; j < (int)FX_DEVMON_BitColumnCount(); j++) {
            offset += HTML_PACK(temp_buffer, offset, "<td>&nbsp;</td>\r\n");
        }
        
        /* 空行的"值"列：与数据行一样只占 1 个单元格（原实现多出一格，空行比数据行宽 1 列）。 */
        offset += HTML_PACK(temp_buffer, offset, "<td>&nbsp;</td>\r\n");
        offset += HTML_PACK(temp_buffer, offset, "</tr>\r\n");
        
        if (offset > 450) {
            Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
            offset = 0;
        }
    }
    
    /* 发送剩余数据 */
    if (offset > 0) {
        Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    }

}
/*********************************************************************
 * @fn      FX_DEVMON_SendData_Table
 *
 * @brief   发送数据表格表头
 *
 * @param   Dest_Sock - Socket ID
 *
 * @return  none
 */
static void FX_DEVMON_SendData_Table(uint8_t Dest_Sock)
{
    /* 发送数据表格表头 */
    char *buffer = HtmlBuffer;
    uint32_t offset = 0;
    uint8_t num = 0;
    // 表格容器
    offset += HTML_PACK(buffer, offset, "<div style=\"overflow:auto; height:400px; width:840px; margin:0 auto\">\r\n");
    // 表格开始
    offset += HTML_PACK(buffer, offset, "<table border=\"1\" rules=\"all\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed; font-size:12px\">\r\n");
    // 表头开始
    offset += HTML_PACK(buffer, offset, "<thead>\r\n");
    
    // 第一列标题
    offset += HTML_PACK(buffer, offset, "<tr>\r\n<td width=\"80\">%s</td>\r\n", 
                     (g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE) ? "软元件" : "缓冲存储器");
    
    /* 数据位列标题：列数统一由"软元件类别 + 监视格式"决定（表头/数据行/空行三处共用同一函数，
     * 原实现各写一套 switch，导致空行列数与数据行不一致、表格错位）。 */
    num = FX_DEVMON_BitColumnCount();
    for (int i = 0; i < num; i++) {
        //位顺序
        if( g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_0F)  /* 0-F */
        {
            offset += HTML_PACK(buffer, offset, "<td width=\"40\">%X</td>", i);
        }else{ /* F-0 */
            offset += HTML_PACK(buffer, offset, "<td width=\"40\">%X</td>", (num - 1 - i) );
        }
    }
    // 值列标题
    offset += HTML_PACK(buffer, offset, "\r\n<td width=\"110\">值</td>\r\n");
    // 表头行结束
    offset += HTML_PACK(buffer, offset, "</tr>\r\n");
    // 表头结束
    offset += HTML_PACK(buffer, offset, "</thead>\r\n");
    // 表体开始
    offset += HTML_PACK(buffer, offset, "<tbody>\r\n");
    
    // 发送数据
    Data_Send(Dest_Sock, (uint8_t*)buffer, offset);
}

/*********************************************************************
 * @fn      FX_DEVMON_SendWebPage
 *
 * @brief   流式发送Web页面 (避免在RAM中存储完整页面)
 *
 * @param   Dest_Sock - Socket ID
 *          url - URL字符串(未使用)
 *
 * @return  none
 */
void FX_DEVMON_SendWebPage(uint8_t Sour_Sock, uint8_t Dest_Sock, char *url, uint8_t fetch_data)
{
    /* ★ 渲染前先归一化配置：字软元件固定为"位＆字"、位软元件固定为"16 位整数"显示，
     *   使表单选项、取数长度、表头列数、数据行渲染四者保持一致（见函数注释）。 */
    FX_DEVMON_NormalizeConfig();

    char *temp_buffer = HtmlBuffer;  /* 使用HtmlBuffer作为发送缓冲区 */
    char *monitor_status;
    uint32_t offset;

    /* ★ fetch_data 决定本次渲染是否发起新的 PLC 批量读：
     *   浏览器请求路径传 1 —— 渲染前取一次最新数据；
     *   UART 回帧路径传 0 —— 只把刚收到的数据渲染出来，绝不再发起读取。
     * 若回帧路径也发读，就会形成 回帧->渲染(发读)->回帧->渲染(发读)->... 的自激循环：
     * 页面不断重发、UART 请求队列被刷满，最终看门狗复位(现场表现即"切到该页就重启")。
     * 数据更新由 UART 分发的 FX_DEVMON_UpdateMonitor_Data() 完成，
     * 浏览器每 5s 自动刷新，因此回帧路径无需重新取数。 */
    if (fetch_data) {
        FX_DEVMON_UpdateMonitor_CMD(Sour_Sock, Dest_Sock);
    }

    /* 获取监控状态 */
    monitor_status  = (char*) HTML_GetStateString(net_monitor_state);
    /* 发送HTTP响应头 */
    SendHttpHeader(Dest_Sock, PTYPE_HTML);
    
    /* 第一次打包: HTML头部（与 CSS 拆开，以在 </head> 之前插入自动更新 meta） */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, HTML_GetComponent(HTML_COMP_HEADER), "软元件/缓冲存储器批量监视");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    /* ★ 只有"监视执行中"才注入 meta refresh：
     *   执行中 -> 浏览器按间隔主动刷新，持续取数(自适应轮询)；
     *   停止   -> 不注入刷新标签，页面只被被动 GET/POST 刷新，
     *             不再无谓地占用网络与 UART 请求队列。 */
    if (net_monitor_state == FX_MONITOR_RUNNING) {
        uint16_t itv = g_monitor_config.update_interval;
        if (itv < 5u || itv > 120u) {
            itv = 5u;
        }
        offset = 0;
        offset += HTML_PACK(temp_buffer, offset, "<meta http-equiv=\"refresh\" content=\"%u\">\r\n", itv);
        Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    }

    /* 第二次打包: CSS 样式表 */
    offset = 0;
    /* CSS 样式表直发：组件 >1.2KB，HtmlBuffer 装不下(越界会写穿 BSS 导致死机) */
    Data_Send(Dest_Sock, (uint8_t*)HTML_GetComponent(HTML_COMP_CSS_NEW),
              strlen(HTML_GetComponent(HTML_COMP_CSS_NEW)));

    /* 第二次打包: body开始到导航栏结束 (使用共享组件) */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "%s", HTML_GetComponent(HTML_COMP_BODY_START_NEW));
    offset += HTML_PACK(temp_buffer, offset, "%s", HTML_GetComponent(HTML_COMP_NAV_BAR_NEW));
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第四次打包: 表单标题 - 添加居中容器 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<div style=\"margin:0 auto; width:840px; text-align:center\">\r\n");
    offset += HTML_PACK(temp_buffer, offset, "<form action=\"fx_devmon.html\" method=\"post\" style=\"display:inline-block; text-align:left\">\r\n<font style=\"font-size=16px\"><b>软元件/缓冲存储器批量监视</b></font>\r\n<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"table-layout:fixed; font-size:14px; margin:0 auto\">\r\n<tbody>\r\n<tr>\r\n<td width=\"20\"></td><td width=\"140\"></td><td width=\"160\"></td><td width=\"80\"></td>\r\n<td width=\"100\"></td><td width=\"100\"></td><td width=\"80\"></td><td width=\"100\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第五次打包: 软元件配置行 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"5\">软元件</td>\r\n<td colspan=\"3\" align=\"right\">状态 :&nbsp;%s</td>\r\n</tr>\r\n", monitor_status);//监控状态
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"2\"><input type=\"radio\" name=\"MONT\" value=\"D\" %s>软元件名</td>\r\n", g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"3\">\r\n<select size=\"1\" name=\"DEVT\">\r\n<option %s>D</option>\r\n<option %s>R</option>\r\n<option %s>X</option>\r\n<option %s>Y</option>\r\n<option %s>M</option>\r\n<option %s>S</option>\r\n<option %s>T</option>\r\n<option %s>C</option>\r\n</select>\r\n", g_monitor_config.device_type == FX_DEVMON_DEV_D ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_R ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_X ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_Y ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_M ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_S ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_T ? "selected" : "", g_monitor_config.device_type == FX_DEVMON_DEV_C ? "selected" : "");
    offset += HTML_PACK(temp_buffer, offset, "<input type=\"text\" size=\"5\" maxlength=\"5\" name=\"DEVN\" value=\"%d\"></td>\r\n<td colspan=\"3\" align=\"right\"><input type=\"submit\" name=\"CMD\" value=\"监视开始\" style=\"width:120;font-weight:bold\"></td>\r\n</tr>\r\n", g_monitor_config.device_number);//监视开始按钮
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第六次打包: 缓冲存储器配置行 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"2\"><input type=\"radio\" name=\"MONT\" value=\"B\" %s>缓冲存储器</td>\r\n", g_monitor_config.monitor_type == FX_DEVMON_MONITOR_BUFFER ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\">模块起始 <select size=\"1\" name=\"MDL\" style=\"width:50;\">\r\n<option %s>0</option>\r\n<option %s>1</option>\r\n<option %s>2</option>\r\n<option %s>3</option>\r\n<option %s>4</option>\r\n<option %s>5</option>\r\n<option %s>6</option>\r\n<option %s>7</option>\r\n</select></td>\r\n", g_monitor_config.buffer_module == 0 ? "selected" : "", g_monitor_config.buffer_module == 1 ? "selected" : "", g_monitor_config.buffer_module == 2 ? "selected" : "", g_monitor_config.buffer_module == 3 ? "selected" : "", g_monitor_config.buffer_module == 4 ? "selected" : "", g_monitor_config.buffer_module == 5 ? "selected" : "", g_monitor_config.buffer_module == 6 ? "selected" : "", g_monitor_config.buffer_module == 7 ? "selected" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"2\">地址 <input type=\"text\" size=\"5\" maxlength=\"5\" name=\"BFMN\" value=\"%d\">\r\n<select size=\"1\" name=\"BFMV\"><option %s>10进制</option><option %s>16进制</option></select></td>\r\n", g_monitor_config.buffer_address, g_monitor_config.buffer_hex == 0 ? "selected" : "", g_monitor_config.buffer_hex == 1 ? "selected" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"3\" align=\"right\"><input type=\"submit\" name=\"CMD\" value=\"监视停止\" style=\"width:120;font-weight:bold\"></td>\r\n</tr>\r\n");//监视停止按钮
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    
    /* 第七次打包: 自动更新间隔 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"6\"></td>\r\n<td colspan=\"2\">自动更新间隔时间(5 - 120)</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\">监视格式</td><td colspan=\"1\">显示</td>\r\n<td colspan=\"1\">进制数</td><td colspan=\"2\">位顺序</td>\r\n<td colspan=\"2\"><input type=\"text\" size=\"5\" maxlength=\"3\" name=\"INT\" value=\"%d\">(秒)</td>\r\n</tr>\r\n", g_monitor_config.update_interval);
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第八次打包: 配置选项行1 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"BT\" %s>位</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_BIT ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"16\" %s>16位整数</td>\r\n", g_monitor_config.display == FX_DEVMON_DISP_16BIT ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"VAL\" value=\"D\" %s>10进制</td>\r\n", g_monitor_config.value_format == FX_DEVMON_VAL_DECIMAL ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"BITO\" value=\"0\" %s>0-F</td>\r\n", g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_0F ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"2\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第九次打包: 配置选项行2 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"WD\" %s>位＆字</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_WORD ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"32\" %s>32位整数</td>\r\n", g_monitor_config.display == FX_DEVMON_DISP_32BIT ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"VAL\" value=\"H\" %s>16进制</td>\r\n", g_monitor_config.value_format == FX_DEVMON_VAL_HEX ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"BITO\" value=\"F\" %s>F-0</td>\r\n", g_monitor_config.bit_order == FX_DEVMON_BIT_ORDER_F0 ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"2\"></td>\r\n</tr>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第八次打包: 配置选项行3和4 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"1\"></td><td colspan=\"1\"><input type=\"radio\" name=\"FORM\" value=\"B10\" %s>位(8/10点)</td>\r\n", g_monitor_config.form == FX_DEVMON_FORM_BIT_8_10 ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"REAL\" %s>实数(32位)</td>\r\n<td colspan=\"5\"></td>\r\n</tr>\r\n", g_monitor_config.display == FX_DEVMON_DISP_REAL ? "checked" : "");
    offset += HTML_PACK(temp_buffer, offset, "<tr>\r\n<td colspan=\"2\"></td><td colspan=\"1\"><input type=\"radio\" name=\"DISP\" value=\"ASC\" %s>ASCII字符</td>\r\n<td colspan=\"5\"></td>\r\n</tr>\r\n", g_monitor_config.display == FX_DEVMON_DISP_ASCII ? "checked" : "");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第九次打包: 分页按钮和数据表格开始 */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "</tbody></table><br>\r\n<table align=\"center\"><tbody>\r\n<tr><td><input type=\"submit\" name=\"PAGE_B\" value=\"上一页\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"上一个\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"下一个\" style=\"width:110;font-weight:bold\"></td>\r\n<td>&nbsp;</td>\r\n<td><input type=\"submit\" name=\"PAGE_B\" value=\"下一页\" style=\"width:110;font-weight:bold\"></td>\r\n</tr></tbody></table>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);
    
    /* 第十次打包: 数据表格 - 表头和部分数据行 */
    /* type/notice bar above the table: data kind, value parse mode, boundary notices */
    FX_DEVMON_SendDataNotice(Dest_Sock);

    FX_DEVMON_SendData_Table(Dest_Sock);    

    /* 第十一次打包: 数据表格 - 数据行1-5 */
    FX_DEVMON_SendDataRows(Dest_Sock, 0, 5);

    /* 第十二次打包: 数据表格 - 数据行6-10 */
    FX_DEVMON_SendDataRows(Dest_Sock, 5, 10);

    /* 第十三次打包: 数据表格 - 数据行11-15 */
    FX_DEVMON_SendDataRows(Dest_Sock, 10, 15);

    /* 第十四次打包: 数据表格 - 数据行16-20 */
    FX_DEVMON_SendDataRows(Dest_Sock, 15, 20);

    /* 第十五次打包: 数据表格 - 数据行21-25 */
    FX_DEVMON_SendDataRows(Dest_Sock, 20, 25);

    /* 第十六次打包: 数据表格 - 数据行26-30 */
    FX_DEVMON_SendDataRows(Dest_Sock, 25, 30);

    /* 第十七次打包: 数据表格 - 数据行31-32 + 结束标签和页脚 (使用公共组件) */
    offset = 0;
    offset += HTML_PACK(temp_buffer, offset, "</tbody>\r\n</table>\r\n</div>\r\n</div>\r\n</form>\r\n</body>\r\n</html>\r\n");
    Data_Send(Dest_Sock, (uint8_t*)temp_buffer, offset);

    /* 页脚(含 SX 自检脚本)直发：组件 >1.2KB，远超 HtmlBuffer 容量。
     * 原来与收尾标签挤在同一包(约 1.27KB) -> 越界写穿 http_request / g_access_fifo
     * (其 records 指针被 HTML 文本覆盖) -> 下一次 FX_ACCLOG_AddRecord() 取 conn_id
     * 即 HardFault(mcause=4 未对齐取数, mtval 为文本字节)。 */
    Data_Send(Dest_Sock, (uint8_t*)HTML_GetComponent(HTML_COMP_FOOTER_NEW),
              strlen(HTML_GetComponent(HTML_COMP_FOOTER_NEW)));
      
    DEVMON_DEBUG("软元件监视页面流式发送完成\r\n");
}
/*********************************************************************
 * @fn      FX_DEVMON_METHOD_POST
 *
 * @brief   POST方法 处理POST请求
 * @param   Sour_Sock - Socket ID
 *          Dest_Sock - Socket ID
 *          url - 请求URL
 *
 * @return  none
 */
void FX_DEVMON_METHOD_POST(uint8_t Sour_Sock ,uint8_t  Dest_Sock,  char *http_request)
{
 
    DEVMON_DEBUG("=== 方法2: 使用Content-Length精确提取 ===\n");
    char* body_start = extract_http_body_with_content_length(http_request);
    if (body_start == NULL) {
        DEVMON_DEBUG("请求体:NULL\n");
        return;

    }
    DEVMON_DEBUG("请求体: %s\n\n", body_start);
    // 解析参数
    char *token = strtok(body_start, "&");
    while (token != NULL)
    {
        char *key = token;
        char *value = strchr(token, '=');
        if (value != NULL)
        {
            *value = '\0';
            value++;
            
            // URL解码
            char decoded_value[128] = {0};
            int i = 0, j = 0;
            while (value[i])
            {
                if (value[i] == '%')
                {
                    char hex[3] = {value[i+1], value[i+2], '\0'};
                    decoded_value[j] = (char)strtol(hex, NULL, 16);
                    i += 3;
                }
                else
                {
                    decoded_value[j] = value[i];
                    i++;
                }
                j++;
            }
            
            // 更新配置
            if (strcmp(key, "MONT") == 0)
            {
                if (strcmp(decoded_value, "D") == 0){
                    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_DEVICE;
                    DEVMON_DEBUG("监视类型:%d 使能软元件 \r\n",g_monitor_config.monitor_type);
                }
                else if (strcmp(decoded_value, "B") == 0){
                    g_monitor_config.monitor_type = FX_DEVMON_MONITOR_BUFFER;
                    DEVMON_DEBUG("监视类型:%d 使能 缓冲存储器\r\n",g_monitor_config.monitor_type);
                }

            }
            else if (strcmp(key, "DEVT") == 0)
            {
                if (strcmp(decoded_value, "D") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_D;
                else if (strcmp(decoded_value, "R") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_R;
                else if (strcmp(decoded_value, "X") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_X;
                else if (strcmp(decoded_value, "Y") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_Y;
                else if (strcmp(decoded_value, "M") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_M;
                else if (strcmp(decoded_value, "S") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_S;
                else if (strcmp(decoded_value, "T") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_T;
                else if (strcmp(decoded_value, "C") == 0) g_monitor_config.device_type = FX_DEVMON_DEV_C;
                DEVMON_DEBUG("软元件类型:%d \r\n",g_monitor_config.device_type);
            }
            else if (strcmp(key, "DEVN") == 0)
            {
                /* X/Y 是 8 进制软元件（显示也是 3 位 8 进制），输入按 8 进制解析；其余按 10 进制。
                 * 表单里 DEVT 排在 DEVN 之前，类型此时已确定。 */
                if (g_monitor_config.device_type == FX_DEVMON_DEV_X ||
                    g_monitor_config.device_type == FX_DEVMON_DEV_Y) {
                    g_monitor_config.device_number = (uint16_t)strtol(decoded_value, NULL, 8);
                } else {
                    g_monitor_config.device_number = (uint16_t)atoi(decoded_value);
                }
                DEVMON_DEBUG("软元件编号:%d \r\n",g_monitor_config.device_number);
            }
            else if (strcmp(key, "MDL") == 0)
            {
                g_monitor_config.buffer_module = atoi(decoded_value);
                DEVMON_DEBUG("缓冲存储器: 模块号:%d \r\n",g_monitor_config.buffer_module);
            }
            else if (strcmp(key, "BFMN") == 0)
            {
                g_monitor_config.buffer_address = atoi(decoded_value);
                DEVMON_DEBUG("缓冲存储器: 开始地址:%d \r\n",g_monitor_config.buffer_address);
            }
            else if (strcmp(key, "BFMV") == 0)
            {
                if (strstr(decoded_value, "10") != NULL)
                    g_monitor_config.buffer_hex = 0;
                else if (strstr(decoded_value, "16") != NULL)
                    g_monitor_config.buffer_hex = 1;
                //DEVMON_DEBUG("缓冲存储器: 进制格式:%d \r\n",g_monitor_config.buffer_hex);
            }
            else if (strcmp(key, "INT") == 0)
            {
                g_monitor_config.update_interval = atoi(decoded_value);
                DEVMON_DEBUG("刷新间隔:%d 秒\r\n",g_monitor_config.update_interval);
            }
            else if (strcmp(key, "DISP") == 0)
            {
                if (strcmp(decoded_value, "16") == 0) g_monitor_config.display = FX_DEVMON_DISP_16BIT;
                else if (strcmp(decoded_value, "32") == 0) g_monitor_config.display = FX_DEVMON_DISP_32BIT;
                else if (strcmp(decoded_value, "REAL") == 0) g_monitor_config.display = FX_DEVMON_DISP_REAL;
                else if (strcmp(decoded_value, "ASC") == 0) g_monitor_config.display = FX_DEVMON_DISP_ASCII;
                DEVMON_DEBUG("显示类型:%d \r\n",g_monitor_config.display);
            }
            else if (strcmp(key, "VAL") == 0)
            {
                if (strcmp(decoded_value, "D") == 0) g_monitor_config.value_format = FX_DEVMON_VAL_DECIMAL;
                else if (strcmp(decoded_value, "H") == 0) g_monitor_config.value_format = FX_DEVMON_VAL_HEX;
                DEVMON_DEBUG("进制格式:%d \r\n",g_monitor_config.value_format);
            }
            else if (strcmp(key, "FORM") == 0)
            {
                if (strcmp(decoded_value, "BT") == 0) g_monitor_config.form = FX_DEVMON_FORM_BIT;
                else if (strcmp(decoded_value, "WD") == 0) g_monitor_config.form = FX_DEVMON_FORM_WORD;
                else if (strcmp(decoded_value, "B10") == 0) g_monitor_config.form = FX_DEVMON_FORM_BIT_8_10;
                DEVMON_DEBUG("监视格式：%d \r\n",g_monitor_config.form);
            }
            else if (strcmp(key, "BITO") == 0)
            {
                if (strcmp(decoded_value, "0") == 0) g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_0F;
                else if (strcmp(decoded_value, "F") == 0) g_monitor_config.bit_order = FX_DEVMON_BIT_ORDER_F0;
                DEVMON_DEBUG("大小端模式：%d \r\n",g_monitor_config.bit_order);
            }
            else if (strcmp(key, "CMD") == 0)
            {
                //CMD=%BC%E0%CA%D3%BF%AA%CA%BC
                if (strcmp(decoded_value, "\xBC\xE0\xCA\xD3\xBF\xAA\xCA\xBC") == 0) {
                    FX_ENETINF_SetMonitorState(FX_MONITOR_RUNNING);      //监视开始
                    DEVMON_DEBUG("监视开始按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xBC\xE0\xCA\xD3\xCD\xA3\xD6\xB9") == 0)  {
                    FX_ENETINF_SetMonitorState(FX_MONITOR_STOPPED);      //监视停止
                    DEVMON_DEBUG("监视停止按钮 \r\n");
                }
            }
            else if (strcmp(key, "PAGE_B") == 0)
            {
                //PAGE_B=%C9%CF%D2%BB%D2%B3 上一页
                //PAGE_B=%CF%C2%D2%BB%D2%B3 下一页
                //PAGE_B=%C9%CF%D2%BB%B8%F6 上一个
                //PAGE_B=%CF%C2%D2%BB%B8%F6 下一个
                if (strcmp(decoded_value, "\xC9\xCF\xD2\xBB\xD2\xB3") == 0) {
                    //上一页
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number -= FX_DEVMON_MAX_ROWS;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address -= FX_DEVMON_MAX_ROWS; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("上一页按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xCF\xC2\xD2\xBB\xD2\xB3") == 0)  {
                    //下一页
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number += FX_DEVMON_MAX_ROWS;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address += FX_DEVMON_MAX_ROWS; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("下一页按钮 \r\n");
                }
                if (strcmp(decoded_value, "\xC9\xCF\xD2\xBB\xB8\xF6") == 0) {
                    //上一个
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number -= 1;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address -= 1; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("上一个按钮 \r\n");
                }
                else if(strcmp(decoded_value, "\xCF\xC2\xD2\xBB\xB8\xF6") == 0)  {
                    //下一个
                    if(g_monitor_config.monitor_type == FX_DEVMON_MONITOR_DEVICE ){
                        //软元件
                        g_monitor_config.device_number += 1;  // 软元件编号
                    }else{
                        //缓存器
                        g_monitor_config.buffer_address += 1; // 缓冲存储器地址
                    }
                    DEVMON_DEBUG("下一个按钮 \r\n");
                }

                if(g_monitor_config.device_number <= 0 ){
                    //软元件
                    g_monitor_config.device_number = 0;  // 软元件编号
                }else if(g_monitor_config.device_number >= 32767 ){
                    g_monitor_config.device_number = 32767; // 缓冲存储器地址
                }

                if(g_monitor_config.buffer_address <= 0 ){
                    //缓存器
                    g_monitor_config.buffer_address = 0; // 缓冲存储器地址
                }else if(g_monitor_config.buffer_address >= 4096 ){
                    g_monitor_config.buffer_address = 4096; // 缓冲存储器地址
                }
            }
        }
        token = strtok(NULL, "&");
    }
    free(body_start);      //释放内存
    DEVMON_DEBUG("释放内存 body_start \r\n" );
    // 更新监视器配置
    FX_DEVMON_UpdateMonitor_CMD(Sour_Sock, Dest_Sock);                   // 发送指令获取状态 :更新监视器配置
}
